/*
 * CadastroVendedor.java
 *
 * Created on 31 de Agosto de 2011, 20:04
 */

package View;

import Utilitarios.Validacao;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.MaskFormatter;
import Controle.*;
import Modelo.*;
import org.lavieri.modelutil.cep.WebServiceCep;


/**
 *
 * @author  Familia-Silva
 */
public class CadastroVendedor extends javax.swing.JFrame {
    
    private conexao con_vendedor;
    private int numeroRegistros = 0;
    
    /** Creates new form CadastroVendedor */
    public CadastroVendedor() throws SQLException {
        initComponents();
         setResizable(false);
        con_vendedor = new conexao();
        con_vendedor.conecta();
        con_vendedor.executeSQL("select MAX (cd_vendedor+1) AS Codigo from Vendedor");
        con_vendedor.resultset.next();
        txtcodigo.setText(con_vendedor.resultset.getString("Codigo"));
        lblvalido.setVisible(false);
        lblinvalido.setVisible(false);
        lblvalido1.setVisible(false);
        lblinvalido1.setVisible(false);
        enter();
        Runtime rt = Runtime.getRuntime();
		int MB = 1048576; // total de bytes em 1MB

		double total = rt.maxMemory() / MB;
		double inicio = total - (carregarMemoria()/MB);
		
		//System.out.println(total);
		//System.out.println(inicio);
		
		// Metodo de limpaza
		rt.runFinalization();
		rt.gc();
		
		double fim = total - rt.freeMemory()/ MB;
		System.out.println("Início = " +inicio + "Fim = " + fim);
    }
    public void enter(){
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        lblnome1 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        lblnome2 = new javax.swing.JLabel();
        try
        {
            FormatoCpf = new MaskFormatter("###.###.###-##");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcpf = new JFormattedTextField (FormatoCpf);
        lblnome5 = new javax.swing.JLabel();
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxttel1 = new JFormattedTextField (FormatoTel1);
        lblnome8 = new javax.swing.JLabel();
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxttel2 = new JFormattedTextField (FormatoTel1);
        lblnome9 = new javax.swing.JLabel();
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxttel3 = new JFormattedTextField (FormatoTel1);
        lblnome10 = new javax.swing.JLabel();
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxttel4 = new JFormattedTextField (FormatoTel1);
        lblnome11 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblnome12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtobs = new javax.swing.JTextField();
        lblnome13 = new javax.swing.JLabel();
        lblvalido = new javax.swing.JLabel();
        lblinvalido = new javax.swing.JLabel();
        lblinvalido1 = new javax.swing.JLabel();
        lblvalido1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        try
        {
            FormatoCep = new MaskFormatter("##.###-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcep = new JFormattedTextField (FormatoCep);
        lblnome14 = new javax.swing.JLabel();
        lblnome15 = new javax.swing.JLabel();
        txtlogradouro = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        lblnome17 = new javax.swing.JLabel();
        txtcomplemento = new javax.swing.JTextField();
        lblnome18 = new javax.swing.JLabel();
        txtbairro = new javax.swing.JTextField();
        lblnome19 = new javax.swing.JLabel();
        lblnome20 = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        txtuf = new javax.swing.JTextField();
        lblnome21 = new javax.swing.JLabel();
        btncadastrar = new java.awt.Button();
        btnlimpar = new java.awt.Button();
        btnsair = new java.awt.Button();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Vendedor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        txtcodigo.setEditable(false);
        jPanel2.add(txtcodigo);
        txtcodigo.setBounds(10, 40, 50, 20);

        lblnome1.setText("C\u00f3d.");
        jPanel2.add(lblnome1);
        lblnome1.setBounds(10, 20, 60, 14);

        jPanel2.add(txtnome);
        txtnome.setBounds(70, 40, 260, 20);

        lblnome2.setText("Nome");
        jPanel2.add(lblnome2);
        lblnome2.setBounds(70, 20, 60, 14);

        ftxtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtcpfActionPerformed(evt);
            }
        });
        ftxtcpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtcpfFocusLost(evt);
            }
        });

        jPanel2.add(ftxtcpf);
        ftxtcpf.setBounds(340, 40, 100, 20);

        lblnome5.setText("CPF");
        jPanel2.add(lblnome5);
        lblnome5.setBounds(340, 20, 80, 14);

        ftxttel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxttel1FocusLost(evt);
            }
        });

        jPanel2.add(ftxttel1);
        ftxttel1.setBounds(10, 90, 100, 20);

        lblnome8.setText("Tel.1");
        jPanel2.add(lblnome8);
        lblnome8.setBounds(10, 70, 80, 14);

        jPanel2.add(ftxttel2);
        ftxttel2.setBounds(120, 90, 100, 20);

        lblnome9.setText("Tel.2");
        jPanel2.add(lblnome9);
        lblnome9.setBounds(120, 70, 80, 14);

        jPanel2.add(ftxttel3);
        ftxttel3.setBounds(230, 90, 100, 20);

        lblnome10.setText("Tel.3");
        jPanel2.add(lblnome10);
        lblnome10.setBounds(230, 70, 80, 14);

        jPanel2.add(ftxttel4);
        ftxttel4.setBounds(340, 90, 100, 20);

        lblnome11.setText("Tel.4");
        jPanel2.add(lblnome11);
        lblnome11.setBounds(340, 70, 80, 14);

        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });

        jPanel2.add(txtemail);
        txtemail.setBounds(10, 140, 210, 20);

        lblnome12.setText("Email");
        jPanel2.add(lblnome12);
        lblnome12.setBounds(10, 120, 60, 14);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Endere\u00e7o"));
        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 240, 450, 110);

        jPanel2.add(txtobs);
        txtobs.setBounds(10, 190, 430, 20);

        lblnome13.setText("Observa\u00e7\u00e3o");
        jPanel2.add(lblnome13);
        lblnome13.setBounds(10, 170, 80, 14);

        lblvalido.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblvalido.setForeground(java.awt.Color.blue);
        lblvalido.setText("V\u00e1lido");
        jPanel2.add(lblvalido);
        lblvalido.setBounds(370, 20, 34, 13);

        lblinvalido.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblinvalido.setForeground(java.awt.Color.red);
        lblinvalido.setText("Inv\u00e1lido");
        jPanel2.add(lblinvalido);
        lblinvalido.setBounds(370, 20, 50, 13);

        lblinvalido1.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblinvalido1.setForeground(java.awt.Color.red);
        lblinvalido1.setText("Inv\u00e1lido");
        jPanel2.add(lblinvalido1);
        lblinvalido1.setBounds(50, 120, 50, 10);

        lblvalido1.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblvalido1.setForeground(java.awt.Color.blue);
        lblvalido1.setText("V\u00e1lido");
        jPanel2.add(lblvalido1);
        lblvalido1.setBounds(50, 120, 34, 13);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 450, 220);

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endere\u00e7o"));
        ftxtcep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtcepFocusLost(evt);
            }
        });

        jPanel1.add(ftxtcep);
        ftxtcep.setBounds(10, 50, 80, 20);

        lblnome14.setText("CEP");
        jPanel1.add(lblnome14);
        lblnome14.setBounds(10, 30, 80, 14);

        lblnome15.setText("Logradouro");
        jPanel1.add(lblnome15);
        lblnome15.setBounds(100, 30, 110, 14);

        jPanel1.add(txtlogradouro);
        txtlogradouro.setBounds(100, 50, 270, 20);

        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });

        jPanel1.add(txtnumero);
        txtnumero.setBounds(380, 50, 60, 20);

        lblnome17.setText("N\u00famero");
        jPanel1.add(lblnome17);
        lblnome17.setBounds(380, 30, 60, 14);

        jPanel1.add(txtcomplemento);
        txtcomplemento.setBounds(10, 100, 100, 20);

        lblnome18.setText("Complemento");
        jPanel1.add(lblnome18);
        lblnome18.setBounds(10, 80, 100, 14);

        jPanel1.add(txtbairro);
        txtbairro.setBounds(120, 100, 120, 20);

        lblnome19.setText("Bairro");
        jPanel1.add(lblnome19);
        lblnome19.setBounds(120, 80, 100, 14);

        lblnome20.setText("Cidade");
        jPanel1.add(lblnome20);
        lblnome20.setBounds(250, 80, 100, 14);

        jPanel1.add(txtcidade);
        txtcidade.setBounds(250, 100, 150, 20);

        txtuf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtufKeyTyped(evt);
            }
        });

        jPanel1.add(txtuf);
        txtuf.setBounds(410, 100, 30, 20);

        lblnome21.setText("UF");
        jPanel1.add(lblnome21);
        lblnome21.setBounds(410, 80, 30, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 240, 450, 130);

        btncadastrar.setFont(new java.awt.Font("Dialog", 1, 12));
        btncadastrar.setLabel("Cadastrar");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        getContentPane().add(btncadastrar);
        btncadastrar.setBounds(10, 380, 80, 30);

        btnlimpar.setFont(new java.awt.Font("Dialog", 1, 12));
        btnlimpar.setLabel("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        getContentPane().add(btnlimpar);
        btnlimpar.setBounds(100, 380, 80, 30);

        btnsair.setFont(new java.awt.Font("Dialog", 1, 12));
        btnsair.setLabel("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        getContentPane().add(btnsair);
        btnsair.setBounds(190, 380, 80, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-485)/2, (screenSize.height-457)/2, 485, 457);
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
// TODO add your handling code here:
        Pattern p = Pattern.compile(".+@.+\\.[a-z]{2,}+");
        Matcher m = p.matcher(txtemail.getText());
        if (!m.find()){
            lblinvalido1.setVisible(true);
            lblvalido1.setVisible(false);
                     
        } else{
            lblinvalido1.setVisible(false);
            lblvalido1.setVisible(true);
            
            
            
        }
    }//GEN-LAST:event_txtemailFocusLost
  public static long carregarMemoria(){
		
		ArrayList<Integer> list = new ArrayList<Integer>();
		for(int i = 0; i<1000000; i++){
		list.add(i);	
		}
		return Runtime.getRuntime().freeMemory();
	}      
    private void ftxtcpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcpfFocusLost
// TODO add your handling code here:
        Validacao v = new Validacao();
        
        if (v.calculaCPF(ftxtcpf.getText().replace(".","").replace("-",""))) {
            lblvalido.setVisible(true);
            lblinvalido.setVisible(false);
            //System.out.println(v.calculaCPF(ftxtcpf.getText()));
        } else {
            
            lblvalido.setVisible(false);
            lblinvalido.setVisible(true);
        }
    }//GEN-LAST:event_ftxtcpfFocusLost
    
    private void ftxtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtcpfActionPerformed
// TODO add your handling code here:
        
    }//GEN-LAST:event_ftxtcpfActionPerformed
    
    private void ftxttel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxttel1FocusLost
// TODO add your handling code here:
        ftxttel2.setText(ftxttel1.getText());
        ftxttel3.setText(ftxttel1.getText());
        ftxttel4.setText(ftxttel1.getText());
    }//GEN-LAST:event_ftxttel1FocusLost
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
        txtnome.requestFocus();
    }//GEN-LAST:event_formWindowOpened
    
    private void txtufKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtufKeyTyped
// TODO add your handling code here:
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
        String conteudo = txtuf.getText();
        if (conteudo.length() >= 2) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtufKeyTyped
    
    private void ftxtcepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcepFocusLost
// TODO add your handling code here:
        WebServiceCep cep = WebServiceCep.searchCep(ftxtcep.getText());
        
        if (cep.wasSuccessful()) {
            
            ftxtcep.setText(cep.getCep().toString());
            txtlogradouro.setText(cep.getLogradouroFull().toString());
            txtbairro.setText(cep.getBairro().toString());
            txtcidade.setText(cep.getCidade().toString());
            txtuf.setText(cep.getUf().toString());
        } else {
            
            JOptionPane.showMessageDialog(null, "Erro número  " + cep.getResulCode());
            JOptionPane.showMessageDialog(null, "Descrição do erro " + cep.getResultText());
            
        }
    }//GEN-LAST:event_ftxtcepFocusLost
    
    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
// TODO add your handling code here:
        // Só aceita numero
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnumeroKeyTyped
    
    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        numeroRegistros= Integer.parseInt(txtcodigo.getText());
        try {
            if(txtnome.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Digito o nome!");
            }
            
            else{
                
                
                String sqlintvendedor = "insert into vendedor (cd_vendedor, cd_cpf_vendedor, nm_vendedor) values ('"+Integer.parseInt(txtcodigo.getText())+"','"+
                        ftxtcpf.getText().replace(".","").replace("-","")+"','"+
                        txtnome.getText().toUpperCase()+"')";
                String sqlinsertemail ="insert into email (cd_vendedor, nm_email1) values ('"+Integer.parseInt(txtcodigo.getText())+"','"+
                        txtemail.getText().toLowerCase()+"')";
                String sqlinserttel ="insert into telefone (cd_vendedor, cd_tel1,cd_tel2,cd_tel3,cd_tel4) values ('"+Integer.parseInt(txtcodigo.getText())+"','"+
                        ftxttel1.getText().replace("(","").replace(")","").replace("-","")+"','"+
                        ftxttel2.getText().replace("(","").replace(")","").replace("-","")+"','"+
                        ftxttel3.getText().replace("(","").replace(")","").replace("-","")+"','"+
                        ftxttel4.getText().replace("(","").replace(")","").replace("-","")+"')";
                String sqlinsertendereco ="insert into endereco (cd_vendedor, nm_logradouro, cd_numero, nm_complemento, nm_bairro, " +
                        "nm_cidade, sg_ufederativa, nm_observacao, cd_cep) values ('"+
                        Integer.parseInt(txtcodigo.getText())+"','"+
                        txtlogradouro.getText().toUpperCase()+"','"+
                        txtnumero.getText()+"','"+
                        txtcomplemento.getText().toUpperCase()+"','"+
                        txtbairro.getText().toUpperCase()+"','"+
                        txtcidade.getText().toUpperCase()+"','"+
                        txtuf.getText().toUpperCase()+"','"+
                        txtobs.getText().toUpperCase()+"','"+
                        ftxtcep.getText().replace(".","").replace("-","")+"')";
                
                
                //  JOptionPane.showMessageDialog(null,"sql = "+sqlinsert);
                con_vendedor.statement.executeUpdate(sqlintvendedor);
                con_vendedor.statement.executeUpdate(sqlinsertemail);
                con_vendedor.statement.executeUpdate(sqlinserttel);
                con_vendedor.statement.executeUpdate(sqlinsertendereco);
                JOptionPane.showMessageDialog(null,"Gravação realizado com sucesso!");
                numeroRegistros++;
                txtcodigo.setText(String.valueOf(numeroRegistros));
                txtnome.setText("");
                ftxttel1.setText("");
                ftxttel2.setText("");
                ftxttel4.setText("");
                ftxttel3.setText("");
                ftxtcpf.setText("");
                txtemail.setText("");
                txtobs.setText("");
                ftxtcep.setText("");
                txtlogradouro.setText("");
                txtnumero.setText("");
                txtcomplemento.setText("");
                txtbairro.setText("");
                txtcidade.setText("");
                txtuf.setText("");
                txtnome.requestFocus();
                lblvalido.setVisible(false);
                lblinvalido.setVisible(false);
                lblvalido1.setVisible(false);
                lblinvalido1.setVisible(false);
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"Erro a tentar Gravar o registro..."+erro);
            
        }
    }//GEN-LAST:event_btncadastrarActionPerformed
    
    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed
    
    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        lblvalido.setVisible(false);
        lblinvalido.setVisible(false);
        lblvalido1.setVisible(false);
        lblinvalido1.setVisible(false);
        txtnome.setText("");
        ftxttel1.setText("");
        ftxttel2.setText("");
        ftxttel4.setText("");
        ftxttel3.setText("");
        ftxtcpf.setText("");
        txtemail.setText("");
        txtobs.setText("");
        ftxtcep.setText("");
        txtlogradouro.setText("");
        txtnumero.setText("");
        txtcomplemento.setText("");
        txtbairro.setText("");
        txtcidade.setText("");
        txtuf.setText("");
    }//GEN-LAST:event_btnlimparActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroVendedor().setVisible(true);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btncadastrar;
    private java.awt.Button btnlimpar;
    private java.awt.Button btnsair;
    private javax.swing.JFormattedTextField ftxtcep;
    private javax.swing.JFormattedTextField ftxtcpf;
    private javax.swing.JFormattedTextField ftxttel1;
    private javax.swing.JFormattedTextField ftxttel2;
    private javax.swing.JFormattedTextField ftxttel3;
    private javax.swing.JFormattedTextField ftxttel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblinvalido;
    private javax.swing.JLabel lblinvalido1;
    private javax.swing.JLabel lblnome1;
    private javax.swing.JLabel lblnome10;
    private javax.swing.JLabel lblnome11;
    private javax.swing.JLabel lblnome12;
    private javax.swing.JLabel lblnome13;
    private javax.swing.JLabel lblnome14;
    private javax.swing.JLabel lblnome15;
    private javax.swing.JLabel lblnome17;
    private javax.swing.JLabel lblnome18;
    private javax.swing.JLabel lblnome19;
    private javax.swing.JLabel lblnome2;
    private javax.swing.JLabel lblnome20;
    private javax.swing.JLabel lblnome21;
    private javax.swing.JLabel lblnome5;
    private javax.swing.JLabel lblnome8;
    private javax.swing.JLabel lblnome9;
    private javax.swing.JLabel lblvalido;
    private javax.swing.JLabel lblvalido1;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtlogradouro;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtobs;
    private javax.swing.JTextField txtuf;
    // End of variables declaration//GEN-END:variables
    
    private MaskFormatter FormatoCpf;
    
    private MaskFormatter FormatoTel1;
    
    private MaskFormatter FormatoCep;
    
}
