/*
 * CadastroUsuario1.java
 *
 * Created on 14 de Setembro de 2011, 21:57
 */

package View;

import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.MaskFormatter;
import Controle.*;
import Modelo.*;
import Utilitarios.EncriptaSenha;
import org.lavieri.modelutil.cep.WebServiceCep;
/**
 *
 * @author  Familia-Silva
 */
public class CadastroUsuario1 extends javax.swing.JFrame {
    
    private conexao con_usuario;
    
    /** Creates new form CadastroUsuario1 */
    public CadastroUsuario1() {
        initComponents();
        
        setResizable(false);
        con_usuario = new conexao();
        con_usuario.conecta();
        con_usuario.executeSQL("select * from login");
        enter();
        Runtime rt = Runtime.getRuntime();
        int MB = 1048576; // total de bytes em 1MB
        
        double total = rt.maxMemory() / MB;
        double inicio = total - (carregarMemoria()/MB);
        
        //System.out.println(total);
        //System.out.println(inicio);
        
        // Metodo de limpaza
        rt.runFinalization();
        rt.gc();
        
        double fim = total - rt.freeMemory()/ MB;
        System.out.println("Início = " +inicio + "Fim = " + fim);
    }
    public void enter(){
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel4 = new javax.swing.JLabel();
        txtoperador = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsair = new java.awt.Button();
        btncadastrar = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        txtsenha1 = new javax.swing.JPasswordField();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Usu\u00e1rio");
        jLabel4.setText("Operador");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 20, 60, 14);

        getContentPane().add(txtoperador);
        txtoperador.setBounds(80, 20, 170, 20);

        getContentPane().add(txtusuario);
        txtusuario.setBounds(80, 50, 170, 20);

        jLabel1.setText("Usu\u00e1rio");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 52, 60, 14);

        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 81, 60, 14);

        btnsair.setFont(new java.awt.Font("Dialog", 1, 12));
        btnsair.setLabel("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        getContentPane().add(btnsair);
        btnsair.setBounds(160, 150, 80, 30);

        btncadastrar.setFont(new java.awt.Font("Dialog", 1, 12));
        btncadastrar.setLabel("Cadastrar");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        getContentPane().add(btncadastrar);
        btncadastrar.setBounds(70, 150, 80, 30);

        jLabel3.setText("Confirma");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 114, 60, 14);

        getContentPane().add(txtsenha);
        txtsenha.setBounds(80, 80, 170, 20);

        getContentPane().add(txtsenha1);
        txtsenha1.setBounds(80, 110, 170, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-276)/2, (screenSize.height-225)/2, 276, 225);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
// TODO add your handling code here:
        try {
            
            if(txtoperador.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Digite o operador!");
                txtoperador.requestFocus();
            } else if(txtusuario.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Digite o login!");
                txtusuario.requestFocus();
            } else if(txtsenha.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Digite a senha!");
                txtsenha.requestFocus();
            } else if(!txtsenha1.getText().equals(txtsenha.getText())){
                JOptionPane.showMessageDialog(null,"Senhas diferentes!");
                txtsenha.requestFocus();
                txtsenha.setText("");
                txtsenha1.setText("");
            }else{
                String sqlinsertcor ="INSERT INTO Login (nm_usuario, cd_senha, nm_operador) values ('"+txtusuario.getText()+"','"+
                      EncriptaSenha.encripta(txtsenha.getText())+"', '"+txtoperador.getText().toUpperCase()+"')";
                
                
                
                // JOptionPane.showMessageDialog(null,"sql = "+sqlinsertcor);
                con_usuario.statement.executeUpdate(sqlinsertcor);
                
                JOptionPane.showMessageDialog(null,"Gravação realizado com sucesso!");
                txtoperador.setText("");
                txtsenha.setText("");
                txtsenha1.setText("");
                txtusuario.setText("");
                txtoperador.requestFocus();
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"Erro a tentar Gravar o registro..."+erro);
            
        }
    }//GEN-LAST:event_btncadastrarActionPerformed
    
    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed
    public static long carregarMemoria(){
        
        ArrayList<Integer> list = new ArrayList<Integer>();
        for(int i = 0; i<1000000; i++){
            list.add(i);
        }
        return Runtime.getRuntime().freeMemory();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario1().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btncadastrar;
    private java.awt.Button btnsair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtoperador;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JPasswordField txtsenha1;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
    
}
