/*
 * CadastroCliente.java
 *
 * Created on 30 de Agosto de 2011, 21:10
 */

package View;

import Utilitarios.Validacao;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.MaskFormatter;
import Controle.*;
import Modelo.*;
import org.lavieri.modelutil.cep.WebServiceCep;

/**
 *
 * @author  Familia-Silva
 */
public class CadastroCliente extends javax.swing.JFrame {
    
    private conexao con_cliente;
    private int numeroRegistros = 0;
    
    MaskFormatter FormatoData, FormatoCpf, FormatoCnpj, FormatoCep, FormatoTel1, FormatoTel2, FormatoTel3, FormatoTel4;
    /** Creates new form CadastroCliente */
    public CadastroCliente() throws SQLException {
        initComponents();
        
        con_cliente = new conexao();
        con_cliente.conecta();
        con_cliente.executeSQL("select MAX (cd_cliente+1) AS Codigo from cliente");
        con_cliente.resultset.next();
        txtcodigo.setText(con_cliente.resultset.getString("Codigo"));
        lblvalido.setVisible(false);
        lblinvalido.setVisible(false);
        lblvalido1.setVisible(false);
        lblinvalido1.setVisible(false);
        lblvalido2.setVisible(false);
        lblinvalido2.setVisible(false);
        cmbpessoa.requestFocus();
         setResizable(false);
        enter();
        Runtime rt = Runtime.getRuntime();
		int MB = 1048576; // total de bytes em 1MB

		double total = rt.maxMemory() / MB;
		double inicio = total - (carregarMemoria()/MB);
		
		//System.out.println(total);
		//System.out.println(inicio);
		
		// Metodo de limpaza
		rt.runFinalization();
		rt.gc();
		
		double fim = total - rt.freeMemory()/ MB;
		System.out.println("Início = " +inicio + "Fim = " + fim);
    }
   public static long carregarMemoria(){
		
		ArrayList<Integer> list = new ArrayList<Integer>();
		for(int i = 0; i<1000000; i++){
		list.add(i);	
		}
		return Runtime.getRuntime().freeMemory();
	}     
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        txtlogradouro1 = new javax.swing.JTextField();
        lblnome16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbpessoa = new javax.swing.JComboBox();
        lblnome = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        lblnome1 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        lblnome2 = new javax.swing.JLabel();
        txtrg = new javax.swing.JTextField();
        lblnome3 = new javax.swing.JLabel();
        lblnome4 = new javax.swing.JLabel();
        try
        {
            FormatoCpf = new MaskFormatter("###.###.###-##");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcpf = new JFormattedTextField (FormatoCpf);
        lblnome5 = new javax.swing.JLabel();
        try
        {
            FormatoCnpj = new MaskFormatter("##.###.###/####-##");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcnpj = new JFormattedTextField (FormatoCnpj);
        lblnome7 = new javax.swing.JLabel();
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxttel1 = new JFormattedTextField (FormatoTel1);
        lblnome8 = new javax.swing.JLabel();
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxttel2 = new JFormattedTextField (FormatoTel1);
        lblnome9 = new javax.swing.JLabel();
        try
        {
            FormatoTel1 = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxttel3 = new JFormattedTextField (FormatoTel1);
        lblnome10 = new javax.swing.JLabel();
        ftxttel4 = new javax.swing.JFormattedTextField();
        lblnome11 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblnome12 = new javax.swing.JLabel();
        lblnome13 = new javax.swing.JLabel();
        txtfantasia = new javax.swing.JTextField();
        cmbmes = new javax.swing.JComboBox();
        cmbdia = new javax.swing.JComboBox();
        cmbano = new javax.swing.JComboBox();
        cmbsexo = new javax.swing.JComboBox();
        lblnome6 = new javax.swing.JLabel();
        lblvalido = new javax.swing.JLabel();
        lblinvalido = new javax.swing.JLabel();
        lblinvalido1 = new javax.swing.JLabel();
        lblvalido1 = new javax.swing.JLabel();
        lblinvalido2 = new javax.swing.JLabel();
        lblvalido2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        try
        {
            FormatoCep = new MaskFormatter("##.###-###");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtcep = new JFormattedTextField (FormatoCep);
        lblnome14 = new javax.swing.JLabel();
        lblnome15 = new javax.swing.JLabel();
        txtlogradouro = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        lblnome17 = new javax.swing.JLabel();
        txtcomplemento = new javax.swing.JTextField();
        lblnome18 = new javax.swing.JLabel();
        txtbairro = new javax.swing.JTextField();
        lblnome19 = new javax.swing.JLabel();
        lblnome20 = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        txtuf = new javax.swing.JTextField();
        lblnome21 = new javax.swing.JLabel();
        btncadastrar = new java.awt.Button();
        btnlimpar = new java.awt.Button();
        btnsair = new java.awt.Button();

        lblnome16.setText("Logradouro");

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        cmbpessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "F\u00edsica", "Jur\u00eddica" }));
        cmbpessoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbpessoaItemStateChanged(evt);
            }
        });

        jPanel2.add(cmbpessoa);
        cmbpessoa.setBounds(10, 40, 80, 20);

        lblnome.setText("Pessoa");
        jPanel2.add(lblnome);
        lblnome.setBounds(10, 20, 60, 14);

        txtcodigo.setEditable(false);
        jPanel2.add(txtcodigo);
        txtcodigo.setBounds(100, 40, 50, 20);

        lblnome1.setText("C\u00f3d.");
        jPanel2.add(lblnome1);
        lblnome1.setBounds(100, 20, 60, 14);

        txtnome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomeFocusLost(evt);
            }
        });

        jPanel2.add(txtnome);
        txtnome.setBounds(160, 40, 280, 20);

        lblnome2.setText("Nome");
        jPanel2.add(lblnome2);
        lblnome2.setBounds(160, 20, 60, 14);

        jPanel2.add(txtrg);
        txtrg.setBounds(110, 140, 90, 20);

        lblnome3.setText("RG");
        jPanel2.add(lblnome3);
        lblnome3.setBounds(110, 120, 60, 14);

        lblnome4.setText("Nascimento");
        jPanel2.add(lblnome4);
        lblnome4.setBounds(260, 70, 80, 14);

        ftxtcpf.setEnabled(false);
        ftxtcpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtcpfFocusLost(evt);
            }
        });

        jPanel2.add(ftxtcpf);
        ftxtcpf.setBounds(210, 140, 100, 20);

        lblnome5.setText("CPF");
        jPanel2.add(lblnome5);
        lblnome5.setBounds(210, 120, 80, 14);

        ftxtcnpj.setEnabled(false);
        ftxtcnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtcnpjFocusLost(evt);
            }
        });

        jPanel2.add(ftxtcnpj);
        ftxtcnpj.setBounds(320, 140, 120, 20);

        lblnome7.setText("CNPJ");
        jPanel2.add(lblnome7);
        lblnome7.setBounds(320, 120, 80, 14);

        ftxttel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxttel1FocusLost(evt);
            }
        });

        jPanel2.add(ftxttel1);
        ftxttel1.setBounds(10, 190, 100, 20);

        lblnome8.setText("Tel.1");
        jPanel2.add(lblnome8);
        lblnome8.setBounds(10, 170, 80, 14);

        jPanel2.add(ftxttel2);
        ftxttel2.setBounds(120, 190, 100, 20);

        lblnome9.setText("Tel.2");
        jPanel2.add(lblnome9);
        lblnome9.setBounds(120, 170, 80, 14);

        jPanel2.add(ftxttel3);
        ftxttel3.setBounds(230, 190, 100, 20);

        lblnome10.setText("Tel.3");
        jPanel2.add(lblnome10);
        lblnome10.setBounds(230, 170, 80, 14);

        jPanel2.add(ftxttel4);
        ftxttel4.setBounds(340, 190, 100, 20);

        lblnome11.setText("Nextel -  (ID)");
        jPanel2.add(lblnome11);
        lblnome11.setBounds(340, 170, 80, 14);

        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });

        jPanel2.add(txtemail);
        txtemail.setBounds(10, 240, 210, 20);

        lblnome12.setText("Email");
        jPanel2.add(lblnome12);
        lblnome12.setBounds(10, 220, 60, 14);

        lblnome13.setText("Fantasia");
        jPanel2.add(lblnome13);
        lblnome13.setBounds(10, 70, 80, 14);

        jPanel2.add(txtfantasia);
        txtfantasia.setBounds(10, 90, 240, 20);

        cmbmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M\u00eas", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel2.add(cmbmes);
        cmbmes.setBounds(320, 90, 50, 20);

        cmbdia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbdia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbdiaItemStateChanged(evt);
            }
        });

        jPanel2.add(cmbdia);
        cmbdia.setBounds(260, 90, 50, 20);

        cmbano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941" }));
        cmbano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbanoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbanoFocusLost(evt);
            }
        });

        jPanel2.add(cmbano);
        cmbano.setBounds(380, 90, 60, 20);

        cmbsexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jPanel2.add(cmbsexo);
        cmbsexo.setBounds(10, 140, 90, 20);

        lblnome6.setText("Sexo");
        jPanel2.add(lblnome6);
        lblnome6.setBounds(10, 120, 60, 14);

        lblvalido.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblvalido.setForeground(java.awt.Color.blue);
        lblvalido.setText("V\u00e1lido");
        jPanel2.add(lblvalido);
        lblvalido.setBounds(239, 121, 34, 13);

        lblinvalido.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblinvalido.setForeground(java.awt.Color.red);
        lblinvalido.setText("Inv\u00e1lido");
        jPanel2.add(lblinvalido);
        lblinvalido.setBounds(240, 120, 50, 13);

        lblinvalido1.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblinvalido1.setForeground(java.awt.Color.red);
        lblinvalido1.setText("Inv\u00e1lido");
        jPanel2.add(lblinvalido1);
        lblinvalido1.setBounds(360, 120, 50, 13);

        lblvalido1.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblvalido1.setForeground(java.awt.Color.blue);
        lblvalido1.setText("V\u00e1lido");
        jPanel2.add(lblvalido1);
        lblvalido1.setBounds(360, 120, 34, 13);

        lblinvalido2.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblinvalido2.setForeground(java.awt.Color.red);
        lblinvalido2.setText("Inv\u00e1lido");
        jPanel2.add(lblinvalido2);
        lblinvalido2.setBounds(50, 220, 50, 13);

        lblvalido2.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblvalido2.setForeground(java.awt.Color.blue);
        lblvalido2.setText("V\u00e1lido");
        jPanel2.add(lblvalido2);
        lblvalido2.setBounds(50, 220, 34, 13);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 450, 270);

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endere\u00e7o"));
        ftxtcep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtcepFocusLost(evt);
            }
        });

        jPanel1.add(ftxtcep);
        ftxtcep.setBounds(10, 50, 80, 20);

        lblnome14.setText("CEP");
        jPanel1.add(lblnome14);
        lblnome14.setBounds(10, 30, 80, 14);

        lblnome15.setText("Logradouro");
        jPanel1.add(lblnome15);
        lblnome15.setBounds(100, 30, 110, 14);

        jPanel1.add(txtlogradouro);
        txtlogradouro.setBounds(100, 50, 270, 20);

        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });

        jPanel1.add(txtnumero);
        txtnumero.setBounds(380, 50, 60, 20);

        lblnome17.setText("N\u00famero");
        jPanel1.add(lblnome17);
        lblnome17.setBounds(380, 30, 60, 14);

        jPanel1.add(txtcomplemento);
        txtcomplemento.setBounds(10, 100, 100, 20);

        lblnome18.setText("Complemento");
        jPanel1.add(lblnome18);
        lblnome18.setBounds(10, 80, 100, 14);

        jPanel1.add(txtbairro);
        txtbairro.setBounds(120, 100, 120, 20);

        lblnome19.setText("Bairro");
        jPanel1.add(lblnome19);
        lblnome19.setBounds(120, 80, 100, 14);

        lblnome20.setText("Cidade");
        jPanel1.add(lblnome20);
        lblnome20.setBounds(250, 80, 100, 14);

        jPanel1.add(txtcidade);
        txtcidade.setBounds(250, 100, 150, 20);

        txtuf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtufKeyTyped(evt);
            }
        });

        jPanel1.add(txtuf);
        txtuf.setBounds(410, 100, 30, 20);

        lblnome21.setText("UF");
        jPanel1.add(lblnome21);
        lblnome21.setBounds(410, 80, 30, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 280, 450, 130);

        btncadastrar.setFont(new java.awt.Font("Dialog", 1, 12));
        btncadastrar.setLabel("Cadastrar");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        getContentPane().add(btncadastrar);
        btncadastrar.setBounds(10, 420, 80, 30);

        btnlimpar.setFont(new java.awt.Font("Dialog", 1, 12));
        btnlimpar.setLabel("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        getContentPane().add(btnlimpar);
        btnlimpar.setBounds(100, 420, 80, 30);

        btnsair.setFont(new java.awt.Font("Dialog", 1, 12));
        btnsair.setLabel("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        getContentPane().add(btnsair);
        btnsair.setBounds(190, 420, 80, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-485)/2, (screenSize.height-499)/2, 485, 499);
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
// TODO add your handling code here:
        Pattern p = Pattern.compile(".+@.+\\.[a-z]{2,}+");
        Matcher m = p.matcher(txtemail.getText());
        if (!m.find()){
            lblinvalido2.setVisible(true);
            lblvalido2.setVisible(false);
            
        } else{
            lblinvalido2.setVisible(false);
            lblvalido2.setVisible(true);
            
            
            
        }
    }//GEN-LAST:event_txtemailFocusLost
    
    private void ftxtcnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcnpjFocusLost
// TODO add your handling code here:
        Validacao v = new Validacao();
        
        if (v.calculaCNPJ(ftxtcnpj.getText().replace(".","").replace("/","").replace("-",""))) {
            lblvalido1.setVisible(true);
            lblinvalido1.setVisible(false);
            
        } else {
            
            lblvalido1.setVisible(false);
            
            lblinvalido1.setVisible(true);
        }
        
    }//GEN-LAST:event_ftxtcnpjFocusLost
    
    private void ftxtcpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcpfFocusLost
// TODO add your handling code here:
        Validacao v = new Validacao();
        
        if (v.calculaCPF(ftxtcpf.getText().replace(".","").replace("-",""))) {
            lblvalido.setVisible(true);
            lblinvalido.setVisible(false);
            //System.out.println(v.calculaCPF(ftxtcpf.getText()));
        } else {
            
            lblvalido.setVisible(false);
            
            lblinvalido.setVisible(true);
        }
    }//GEN-LAST:event_ftxtcpfFocusLost
    
    private void ftxttel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxttel1FocusLost
// TODO add your handling code here:
        ftxttel2.setText(ftxttel1.getText());
        ftxttel3.setText(ftxttel1.getText());
        ftxttel4.setText(ftxttel1.getText());
    }//GEN-LAST:event_ftxttel1FocusLost
    
    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed
    public void enter(){
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }
    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        lblvalido.setVisible(false);
        lblinvalido.setVisible(false);
        lblvalido1.setVisible(false);
        lblinvalido1.setVisible(false);
        lblvalido2.setVisible(false);
        lblinvalido2.setVisible(false);
        txtnome.setText("");
        txtfantasia.setText("");
        ftxtcnpj.setText("");
        ftxttel1.setText("");
        ftxttel2.setText("");
        ftxttel4.setText("");
        ftxttel3.setText("");
        ftxtcpf.setText("");
        ftxtcnpj.setText("");
        ftxtcpf.setEnabled(false);
        ftxtcnpj.setEnabled(false);
        txtemail.setText("");
        txtrg.setText("");
        ftxtcep.setText("");
        txtlogradouro.setText("");
        txtnumero.setText("");
        txtcomplemento.setText("");
        txtbairro.setText("");
        txtcidade.setText("");
        txtuf.setText("");
        cmbpessoa.setSelectedIndex(0);
        cmbsexo.setSelectedIndex(0);
        cmbdia.setSelectedIndex(0);
        cmbmes.setSelectedIndex(0);
        cmbano.setSelectedIndex(0);
        cmbpessoa.requestFocus();
    }//GEN-LAST:event_btnlimparActionPerformed
    
    private void ftxtcepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtcepFocusLost
        WebServiceCep cep = WebServiceCep.searchCep(ftxtcep.getText());
        
        if (cep.wasSuccessful()) {
            
            ftxtcep.setText(cep.getCep().toString());
            txtlogradouro.setText(cep.getLogradouroFull().toString());
            txtbairro.setText(cep.getBairro().toString());
            txtcidade.setText(cep.getCidade().toString());
            txtuf.setText(cep.getUf().toString());
        } else {
            
            JOptionPane.showMessageDialog(null, "Erro número  " + cep.getResulCode());
            JOptionPane.showMessageDialog(null, "Descrição do erro " + cep.getResultText());
            
        }
    }//GEN-LAST:event_ftxtcepFocusLost
    
    private void txtufKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtufKeyTyped
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
        String conteudo = txtuf.getText();
        if (conteudo.length() >= 2) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtufKeyTyped
    
    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
// Só aceita numero
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnumeroKeyTyped
    
    private void txtnomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomeFocusLost
        txtfantasia.setText(txtnome.getText());
    }//GEN-LAST:event_txtnomeFocusLost
    
    private void cmbpessoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbpessoaItemStateChanged
        if(cmbpessoa.getSelectedItem().equals("Física")){
            
            ftxtcpf.setEnabled(true);
            ftxtcnpj.setEnabled(false);
        }
        if(cmbpessoa.getSelectedItem().equals("Jurídica")){
            
            ftxtcpf.setEnabled(false);
            ftxtcnpj.setEnabled(true);
        }
        
    }//GEN-LAST:event_cmbpessoaItemStateChanged
    
    private void cmbanoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbanoFocusGained
        
    }//GEN-LAST:event_cmbanoFocusGained
    
    private void cmbdiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbdiaItemStateChanged
        
        
    }//GEN-LAST:event_cmbdiaItemStateChanged
    
    private void cmbanoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbanoFocusLost
        
        
    }//GEN-LAST:event_cmbanoFocusLost
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
    
    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {
        
        //código para Gravar os dados no Banco de Dados
        numeroRegistros= Integer.parseInt(txtcodigo.getText());
        try {
            
            if(cmbdia.getSelectedItem().equals("Dia") ||cmbmes.getSelectedItem().equals("Mês")||cmbano.getSelectedItem().equals("Ano")||cmbpessoa.getSelectedItem().equals("-")){
                
                JOptionPane.showMessageDialog(null,"Selecionar Pessoa, Dia, Mês e Ano!");
                cmbdia.requestFocus();
            } else{
                String sqlinsertcliente ="insert into cliente (cd_cliente, cd_cpf_cliente, cd_cnpj_cliente, nm_cliente, nm_fantasia_cliente, " +
                        "cd_rg_cliente, ic_sexo_cliente, dt_dia_nascimento, dt_mes_nascimento, dt_ano_nascimento) values ('"+
                        Integer.parseInt(txtcodigo.getText())+"','"+
                        ftxtcpf.getText().replace(".","").replace("-","")+"','"+
                        ftxtcnpj.getText().replace(".","").replace("-","").replace("/","")+"','"+
                        txtnome.getText().toUpperCase()+"','"+
                        txtfantasia.getText().toUpperCase()+"','"+
                        txtrg.getText().replace(".","").replace("-","")+"','"+
                        cmbsexo.getSelectedItem().toString().toUpperCase()+"','"+
                        cmbdia.getSelectedItem()+"','"+
                        cmbmes.getSelectedItem()+"','"+
                        cmbano.getSelectedItem()+"')";
                String sqlinsertemail ="insert into email (cd_cliente, nm_email1) values ('"+Integer.parseInt(txtcodigo.getText())+"','"+
                        txtemail.getText().toLowerCase()+"')";
                String sqlinserttel ="insert into telefone (cd_cliente, cd_tel1,cd_tel2,cd_tel3,cd_tel4) values ('"+Integer.parseInt(txtcodigo.getText())+"','"+
                        ftxttel1.getText().replace("(","").replace(")","").replace("-","")+"','"+
                        ftxttel2.getText().replace("(","").replace(")","").replace("-","")+"','"+
                        ftxttel3.getText().replace("(","").replace(")","").replace("-","")+"','"+
                        ftxttel4.getText().replace("(","").replace(")","").replace("-","")+"')";
                String sqlinsertendereco ="insert into endereco (cd_cliente, nm_logradouro, cd_numero, nm_complemento, nm_bairro, " +
                        "nm_cidade, sg_ufederativa, nm_observacao, cd_cep) values ('"+
                        Integer.parseInt(txtcodigo.getText())+"','"+
                        txtlogradouro.getText().toUpperCase()+"','"+
                        txtnumero.getText()+"','"+
                        txtcomplemento.getText().toUpperCase()+"','"+
                        txtbairro.getText().toUpperCase()+"','"+
                        txtcidade.getText().toUpperCase()+"','"+
                        txtuf.getText().toUpperCase()+"','"+
                        " "+"','"+
                        ftxtcep.getText().replace(".","").replace("-","")+"')";
                
                
                
                
                con_cliente.statement.executeUpdate(sqlinsertcliente);
                con_cliente.statement.executeUpdate(sqlinsertemail);
                con_cliente.statement.executeUpdate(sqlinserttel);
                con_cliente.statement.executeUpdate(sqlinsertendereco);
                JOptionPane.showMessageDialog(null,"Gravação realizado com sucesso!");
                numeroRegistros++;
                txtcodigo.setText(String.valueOf(numeroRegistros));
                txtnome.setText("");
                txtfantasia.setText("");
                ftxtcnpj.setText("");
                ftxttel1.setText("");
                ftxttel2.setText("");
                ftxttel4.setText("");
                ftxttel3.setText("");
                ftxtcpf.setText("");
                ftxtcnpj.setText("");
                ftxtcpf.setEnabled(false);
                ftxtcnpj.setEnabled(false);
                txtemail.setText("");
                txtrg.setText("");
                ftxtcep.setText("");
                txtlogradouro.setText("");
                txtnumero.setText("");
                txtcomplemento.setText("");
                txtbairro.setText("");
                txtcidade.setText("");
                txtuf.setText("");
                cmbpessoa.setSelectedIndex(0);
                cmbsexo.setSelectedIndex(0);
                cmbdia.setSelectedIndex(0);
                cmbmes.setSelectedIndex(0);
                cmbano.setSelectedIndex(0);
                lblvalido.setVisible(false);
                lblinvalido.setVisible(false);
                lblvalido1.setVisible(false);
                lblinvalido1.setVisible(false);
                lblvalido2.setVisible(false);
                lblinvalido2.setVisible(false);
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"Erro a tentar Gravar o registro..."+erro);
            
        }
        
        
        
// TODO add your handling code here:
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroCliente().setVisible(true);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btncadastrar;
    private java.awt.Button btnlimpar;
    private java.awt.Button btnsair;
    private javax.swing.JComboBox cmbano;
    private javax.swing.JComboBox cmbdia;
    private javax.swing.JComboBox cmbmes;
    private javax.swing.JComboBox cmbpessoa;
    private javax.swing.JComboBox cmbsexo;
    private javax.swing.JFormattedTextField ftxtcep;
    private javax.swing.JFormattedTextField ftxtcnpj;
    private javax.swing.JFormattedTextField ftxtcpf;
    private javax.swing.JFormattedTextField ftxttel1;
    private javax.swing.JFormattedTextField ftxttel2;
    private javax.swing.JFormattedTextField ftxttel3;
    private javax.swing.JFormattedTextField ftxttel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblinvalido;
    private javax.swing.JLabel lblinvalido1;
    private javax.swing.JLabel lblinvalido2;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblnome1;
    private javax.swing.JLabel lblnome10;
    private javax.swing.JLabel lblnome11;
    private javax.swing.JLabel lblnome12;
    private javax.swing.JLabel lblnome13;
    private javax.swing.JLabel lblnome14;
    private javax.swing.JLabel lblnome15;
    private javax.swing.JLabel lblnome16;
    private javax.swing.JLabel lblnome17;
    private javax.swing.JLabel lblnome18;
    private javax.swing.JLabel lblnome19;
    private javax.swing.JLabel lblnome2;
    private javax.swing.JLabel lblnome20;
    private javax.swing.JLabel lblnome21;
    private javax.swing.JLabel lblnome3;
    private javax.swing.JLabel lblnome4;
    private javax.swing.JLabel lblnome5;
    private javax.swing.JLabel lblnome6;
    private javax.swing.JLabel lblnome7;
    private javax.swing.JLabel lblnome8;
    private javax.swing.JLabel lblnome9;
    private javax.swing.JLabel lblvalido;
    private javax.swing.JLabel lblvalido1;
    private javax.swing.JLabel lblvalido2;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfantasia;
    private javax.swing.JTextField txtlogradouro;
    private javax.swing.JTextField txtlogradouro1;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtrg;
    private javax.swing.JTextField txtuf;
    // End of variables declaration//GEN-END:variables
    
}

