/*
 * ConsultaCliente.java
 *
 * Created on 5 de Setembro de 2011, 20:03
 */

package View;

import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.MaskFormatter;
import Controle.*;
import Modelo.*;
import org.lavieri.modelutil.cep.WebServiceCep;

/**
 *
 * @author  Familia-Silva
 */
public class ConsultaReceberCliente extends javax.swing.JFrame {
   private MaskFormatter FormatoData, FormatoCpf, FormatoCnpj, FormatoCep, FormatoTel1, FormatoTel2, FormatoTel3, FormatoTel4;
    private conexao con_cliente, con_receber, con_telefone, con_email;
    
    
    
    public ConsultaReceberCliente() {
        initComponents();
        
        Runtime rt = Runtime.getRuntime();
		int MB = 1048576; // total de bytes em 1MB

		
		
		double total = rt.maxMemory() / MB;
		double inicio = total - (carregarMemoria()/MB);
		
		//System.out.println(total);
		//System.out.println(inicio);
		
		// Metodo de limpaza
		rt.runFinalization();
		rt.gc();
		
		double fim = total - rt.freeMemory()/ MB;
		System.out.println("Início = " +inicio + "Fim = " + fim);
       
        enter();
        con_cliente=new conexao();
        con_cliente.conecta();
         setResizable(false);
        con_receber=new conexao();
        con_receber.conecta();
        con_receber.executeSQL("Select * FROM contareceber1 order by cd_cliente");
        con_receber.executeSQL("Select * from vendacarteira order by cd_vendacarteira");
        con_cliente.executeSQL("Select cd_cliente, nm_cliente FROM Cliente order by nm_cliente");
     
        try {
            while(con_cliente.resultset.next())
                cmbnome.addItem(con_cliente.resultset.getString("nm_cliente"));
            
            
        } catch(SQLException erro) {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }
    }
     public static long carregarMemoria(){
		
		ArrayList<Integer> list = new ArrayList<Integer>();
		for(int i = 0; i<1000000; i++){
		list.add(i);	
		}
		return Runtime.getRuntime().freeMemory();
	}   
    public void enter(){
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    } 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbnome = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        try
        {
            FormatoData = new MaskFormatter("##/##/####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtvenda = new JFormattedTextField (FormatoData);
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtparcela1 = new javax.swing.JTextField();
        txtparcela2 = new javax.swing.JTextField();
        txtparcela3 = new javax.swing.JTextField();
        txtparcela4 = new javax.swing.JTextField();
        txtparcela5 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        try
        {
            FormatoData = new MaskFormatter("##/##/####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtvencimento1 = new JFormattedTextField (FormatoData);
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        try
        {
            FormatoData = new MaskFormatter("##/##/####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtvencimento2 = new JFormattedTextField (FormatoData);
        try
        {
            FormatoData = new MaskFormatter("##/##/####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtvencimento3 = new JFormattedTextField (FormatoData);
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        try
        {
            FormatoData = new MaskFormatter("##/##/####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtvencimento4 = new JFormattedTextField (FormatoData);
        jLabel17 = new javax.swing.JLabel();
        try
        {
            FormatoData = new MaskFormatter("##/##/####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possível gerar máscara, erro = " +erro);
        }

        ftxtvencimento5 = new JFormattedTextField (FormatoData);
        jPanel19 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        sttparcela1 = new javax.swing.JTextField();
        sttparcela2 = new javax.swing.JTextField();
        sttparcela3 = new javax.swing.JTextField();
        sttparcela4 = new javax.swing.JTextField();
        sttparcela5 = new javax.swing.JTextField();
        btnalterar = new java.awt.Button();
        btnlimpar = new java.awt.Button();
        btnsair = new java.awt.Button();
        btnsair1 = new java.awt.Button();
        txtobs = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conta Receber Cliente - Carteira");
        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        txtcodigo.setEditable(false);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(10, 40, 80, 20);

        jLabel1.setText("C\u00f3digo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 50, 14);

        cmbnome.setMaximumRowCount(5);
        cmbnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnomeActionPerformed(evt);
            }
        });

        jPanel1.add(cmbnome);
        cmbnome.setBounds(110, 40, 420, 20);

        jLabel2.setText("Nome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 20, 50, 14);

        jPanel1.add(ftxtvenda);
        ftxtvenda.setBounds(550, 40, 90, 20);

        jLabel4.setText("Venda");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(550, 20, 70, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 650, 70);

        jPanel3.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanel18.setLayout(null);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor Parcelas"));
        jLabel13.setText("1\u00ba");
        jPanel18.add(jLabel13);
        jLabel13.setBounds(10, 30, 40, 14);

        jLabel18.setText("2\u00ba");
        jPanel18.add(jLabel18);
        jLabel18.setBounds(140, 30, 40, 14);

        jLabel19.setText("3\u00ba");
        jPanel18.add(jLabel19);
        jLabel19.setBounds(270, 30, 40, 14);

        jLabel20.setText("4\u00ba");
        jPanel18.add(jLabel20);
        jLabel20.setBounds(400, 30, 40, 14);

        jLabel21.setText("5\u00ba");
        jPanel18.add(jLabel21);
        jLabel21.setBounds(520, 30, 40, 14);

        txtparcela1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtparcela1FocusGained(evt);
            }
        });
        txtparcela1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtparcela1KeyReleased(evt);
            }
        });

        jPanel18.add(txtparcela1);
        txtparcela1.setBounds(40, 30, 70, 20);

        txtparcela2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtparcela2FocusGained(evt);
            }
        });
        txtparcela2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtparcela2KeyReleased(evt);
            }
        });

        jPanel18.add(txtparcela2);
        txtparcela2.setBounds(170, 30, 70, 20);

        txtparcela3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtparcela3FocusGained(evt);
            }
        });
        txtparcela3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtparcela3KeyReleased(evt);
            }
        });

        jPanel18.add(txtparcela3);
        txtparcela3.setBounds(300, 30, 70, 20);

        txtparcela4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtparcela4FocusGained(evt);
            }
        });
        txtparcela4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtparcela4KeyReleased(evt);
            }
        });

        jPanel18.add(txtparcela4);
        txtparcela4.setBounds(430, 30, 70, 20);

        txtparcela5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtparcela5FocusGained(evt);
            }
        });
        txtparcela5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtparcela5KeyReleased(evt);
            }
        });

        jPanel18.add(txtparcela5);
        txtparcela5.setBounds(550, 30, 70, 20);

        jPanel3.add(jPanel18);
        jPanel18.setBounds(10, 100, 630, 60);

        jPanel17.setLayout(null);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Vencimento"));
        ftxtvencimento1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtvencimento1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtvencimento1FocusLost(evt);
            }
        });

        jPanel17.add(ftxtvencimento1);
        ftxtvencimento1.setBounds(40, 30, 70, 20);

        jLabel12.setText("1\u00ba");
        jPanel17.add(jLabel12);
        jLabel12.setBounds(10, 30, 40, 14);

        jLabel14.setText("2\u00ba");
        jPanel17.add(jLabel14);
        jLabel14.setBounds(140, 30, 40, 14);

        ftxtvencimento2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtvencimento2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtvencimento2FocusLost(evt);
            }
        });

        jPanel17.add(ftxtvencimento2);
        ftxtvencimento2.setBounds(170, 30, 70, 20);

        ftxtvencimento3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtvencimento3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtvencimento3FocusLost(evt);
            }
        });

        jPanel17.add(ftxtvencimento3);
        ftxtvencimento3.setBounds(300, 30, 70, 20);

        jLabel15.setText("3\u00ba");
        jPanel17.add(jLabel15);
        jLabel15.setBounds(270, 30, 40, 14);

        jLabel16.setText("4\u00ba");
        jPanel17.add(jLabel16);
        jLabel16.setBounds(400, 30, 40, 14);

        ftxtvencimento4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtvencimento4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtvencimento4FocusLost(evt);
            }
        });

        jPanel17.add(ftxtvencimento4);
        ftxtvencimento4.setBounds(430, 30, 70, 20);

        jLabel17.setText("5\u00ba");
        jPanel17.add(jLabel17);
        jLabel17.setBounds(520, 30, 40, 14);

        ftxtvencimento5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtvencimento5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtvencimento5FocusLost(evt);
            }
        });

        jPanel17.add(ftxtvencimento5);
        ftxtvencimento5.setBounds(550, 30, 70, 20);

        jPanel3.add(jPanel17);
        jPanel17.setBounds(10, 30, 630, 60);

        jPanel19.setLayout(null);

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));
        jLabel22.setText("1\u00ba");
        jPanel19.add(jLabel22);
        jLabel22.setBounds(10, 30, 40, 14);

        jLabel23.setText("2\u00ba");
        jPanel19.add(jLabel23);
        jLabel23.setBounds(140, 30, 40, 14);

        jLabel24.setText("3\u00ba");
        jPanel19.add(jLabel24);
        jLabel24.setBounds(270, 30, 40, 14);

        jLabel25.setText("4\u00ba");
        jPanel19.add(jLabel25);
        jLabel25.setBounds(400, 30, 40, 14);

        jLabel26.setText("5\u00ba");
        jPanel19.add(jLabel26);
        jLabel26.setBounds(520, 30, 40, 14);

        sttparcela1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sttparcela1FocusGained(evt);
            }
        });
        sttparcela1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sttparcela1KeyReleased(evt);
            }
        });

        jPanel19.add(sttparcela1);
        sttparcela1.setBounds(40, 30, 70, 20);

        sttparcela2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sttparcela2FocusGained(evt);
            }
        });
        sttparcela2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sttparcela2KeyReleased(evt);
            }
        });

        jPanel19.add(sttparcela2);
        sttparcela2.setBounds(170, 30, 70, 20);

        sttparcela3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sttparcela3FocusGained(evt);
            }
        });
        sttparcela3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sttparcela3KeyReleased(evt);
            }
        });

        jPanel19.add(sttparcela3);
        sttparcela3.setBounds(300, 30, 70, 20);

        sttparcela4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sttparcela4FocusGained(evt);
            }
        });
        sttparcela4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sttparcela4KeyReleased(evt);
            }
        });

        jPanel19.add(sttparcela4);
        sttparcela4.setBounds(430, 30, 70, 20);

        sttparcela5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sttparcela5FocusGained(evt);
            }
        });
        sttparcela5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sttparcela5KeyReleased(evt);
            }
        });

        jPanel19.add(sttparcela5);
        sttparcela5.setBounds(550, 30, 70, 20);

        jPanel3.add(jPanel19);
        jPanel19.setBounds(10, 170, 630, 60);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 80, 650, 240);

        btnalterar.setFont(new java.awt.Font("Dialog", 1, 12));
        btnalterar.setLabel("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        getContentPane().add(btnalterar);
        btnalterar.setBounds(100, 460, 80, 30);

        btnlimpar.setFont(new java.awt.Font("Dialog", 1, 12));
        btnlimpar.setLabel("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        getContentPane().add(btnlimpar);
        btnlimpar.setBounds(190, 460, 80, 30);

        btnsair.setFont(new java.awt.Font("Dialog", 1, 12));
        btnsair.setLabel("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        getContentPane().add(btnsair);
        btnsair.setBounds(280, 460, 80, 30);

        btnsair1.setFont(new java.awt.Font("Dialog", 1, 12));
        btnsair1.setLabel("Consultar");
        btnsair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsair1ActionPerformed(evt);
            }
        });

        getContentPane().add(btnsair1);
        btnsair1.setBounds(10, 460, 80, 30);

        txtobs.setColumns(20);
        txtobs.setRows(5);
        getContentPane().add(txtobs);
        txtobs.setBounds(10, 350, 650, 94);

        jLabel3.setText("Observa\u00e7\u00e3o");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 330, 90, 14);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-677)/2, (screenSize.height-530)/2, 677, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsair1ActionPerformed
// TODO add your handling code here:
SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
        Date data = null;
        Date data1 = null;
        
        try {
            data = (Date) fmt.parse(ftxtvenda.getText());
            
            
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        try {
    if(ftxtvenda.getText().equals("  /  /    ")){
        JOptionPane.showMessageDialog(null,"Digite um data");
        ftxtvenda.requestFocus();
    } else{
            con_receber = new conexao();
           con_receber.conecta();
            con_receber.executeSQL("Select dt_vencimento1, dt_vencimento2, dt_vencimento3, dt_vencimento4, dt_vencimento5, vl_parcela1, vl_parcela2, vl_parcela3, vl_parcela4, vl_parcela5, ds_status1, ds_status2, ds_status3, ds_status4, ds_status5, ds_observacao FROM contareceber1 where cd_cliente='"
                    + txtcodigo.getText() + "' and dt_venda = '" + data + "' order by dt_venda");
               
            con_receber.resultset.first();
           
            ftxtvencimento1.setText(new SimpleDateFormat("dd/MM/yyyy").format(con_receber.resultset.getDate("dt_vencimento1")));  
            ftxtvencimento2.setText(new SimpleDateFormat("dd/MM/yyyy").format(con_receber.resultset.getDate("dt_vencimento2")));
            ftxtvencimento3.setText(new SimpleDateFormat("dd/MM/yyyy").format(con_receber.resultset.getDate("dt_vencimento3")));
            ftxtvencimento4.setText(new SimpleDateFormat("dd/MM/yyyy").format(con_receber.resultset.getDate("dt_vencimento4")));
            ftxtvencimento5.setText(new SimpleDateFormat("dd/MM/yyyy").format(con_receber.resultset.getDate("dt_vencimento5")));
            txtparcela1.setText(converterDoubleString(con_receber.resultset.getDouble("vl_parcela1")));
            txtparcela2.setText(converterDoubleString(con_receber.resultset.getDouble("vl_parcela2")));
            txtparcela3.setText(converterDoubleString(con_receber.resultset.getDouble("vl_parcela3")));
            txtparcela4.setText(converterDoubleString(con_receber.resultset.getDouble("vl_parcela4")));
            txtparcela5.setText(converterDoubleString(con_receber.resultset.getDouble("vl_parcela5")));
            sttparcela1.setText(con_receber.resultset.getString("ds_status1"));
            sttparcela2.setText(con_receber.resultset.getString("ds_status2"));
            sttparcela3.setText(con_receber.resultset.getString("ds_status3"));
            sttparcela4.setText(con_receber.resultset.getString("ds_status4"));
            sttparcela5.setText(con_receber.resultset.getString("ds_status5"));
            txtobs.setText(con_receber.resultset.getString("ds_observacao"));
            
             sttparcela1.setBackground(getBackground().yellow);
              sttparcela2.setBackground(getBackground().yellow);
               sttparcela3.setBackground(getBackground().yellow);
                sttparcela4.setBackground(getBackground().yellow);
                 sttparcela5.setBackground(getBackground().yellow);
                         txtobs.setBackground(getBackground().yellow);
             if(((ftxtvencimento2.getText().equals("11/11/1111")))){
                    ftxtvencimento2.setText("");
            }
             if(((ftxtvencimento3.getText().equals("11/11/1111")))){
                    ftxtvencimento3.setText("");
            }
             if(((ftxtvencimento4.getText().equals("11/11/1111")))){
                    ftxtvencimento4.setText("");
            }
             if(((ftxtvencimento5.getText().equals("11/11/1111")))){
                    ftxtvencimento5.setText("");
            }
             if(((txtparcela2.getText().equals("0.00")))){
                    txtparcela2.setText("");
                     sttparcela2.setBackground(getBackground().white);
            }
            if(((txtparcela3.getText().equals("0.00")))){
                    txtparcela3.setText("");
                    sttparcela3.setBackground(getBackground().white);
            }
            if(((txtparcela4.getText().equals("0.00")))){
                    txtparcela4.setText("");
                    sttparcela4.setBackground(getBackground().white);
            }
            if(((txtparcela5.getText().equals("0.00")))){
                    txtparcela5.setText("");
                    sttparcela5.setBackground(getBackground().white);
            }
             if(((txtparcela2.getText().equals("")))){
                    sttparcela2.setText("");
                    
            }
            if(((txtparcela3.getText().equals("")))){
                    sttparcela3.setText("");
            }
            if(((txtparcela4.getText().equals("")))){
                    sttparcela4.setText("");
            }
            if(((txtparcela5.getText().equals("")))){
                    sttparcela5.setText("");
            }
            if(((sttparcela1.getText().equals("PENDENTE")))){
             String nome = "Deseja alterar o status da parcela 1 ?";
                int opcao_escolha = JOptionPane.showConfirmDialog(null,nome,"Alterar Status Parcela", JOptionPane.YES_NO_OPTION);
                if(opcao_escolha==JOptionPane.YES_OPTION){
                   btnalterar.requestFocus();
                   sttparcela1.setText("PAGA");                   
                }
                if(opcao_escolha==JOptionPane.NO_OPTION){
                        btnalterar.requestFocus();
                      txtobs.requestFocus();
                }         
            }
            if(((sttparcela2.getText().equals("PENDENTE")))){
             String nome = "Deseja alterar o status da parcela 2 ?";
                int opcao_escolha = JOptionPane.showConfirmDialog(null,nome,"Alterar Status Parcela", JOptionPane.YES_NO_OPTION);
                if(opcao_escolha==JOptionPane.YES_OPTION){
                   btnalterar.requestFocus();
                   sttparcela2.setText("PAGA");                   
                }
                if(opcao_escolha==JOptionPane.NO_OPTION){
                        btnalterar.requestFocus();
                      txtobs.requestFocus();
                }         
            }
            if(((sttparcela3.getText().equals("PENDENTE")))){
             String nome = "Deseja alterar o status da parcela 3 ?";
                int opcao_escolha = JOptionPane.showConfirmDialog(null,nome,"Alterar Status Parcela", JOptionPane.YES_NO_OPTION);
                if(opcao_escolha==JOptionPane.YES_OPTION){
                   btnalterar.requestFocus();
                   sttparcela3.setText("PAGA");                   
                }
                if(opcao_escolha==JOptionPane.NO_OPTION){
                        btnalterar.requestFocus();
                      txtobs.requestFocus();
                }         
            }
            if(((sttparcela4.getText().equals("PENDENTE")))){
             String nome = "Deseja alterar o status da parcela 4 ?";
                int opcao_escolha = JOptionPane.showConfirmDialog(null,nome,"Alterar Status Parcela", JOptionPane.YES_NO_OPTION);
                if(opcao_escolha==JOptionPane.YES_OPTION){
                   btnalterar.requestFocus();
                   sttparcela4.setText("PAGA");                   
                }
                if(opcao_escolha==JOptionPane.NO_OPTION){
                        btnalterar.requestFocus();
                      txtobs.requestFocus();
                }         
            }
           if(((sttparcela5.getText().equals("PENDENTE")))){
             String nome = "Deseja alterar o status da parcela 5 ?";
                int opcao_escolha = JOptionPane.showConfirmDialog(null,nome,"Alterar Status Parcela", JOptionPane.YES_NO_OPTION);
                if(opcao_escolha==JOptionPane.YES_OPTION){
                   btnalterar.requestFocus();
                   sttparcela5.setText("PAGA");                   
                }
                if(opcao_escolha==JOptionPane.NO_OPTION){
                        btnalterar.requestFocus();
                      txtobs.requestFocus();
                }         
            }              
           }      
        } catch(SQLException erro) {

      // JOptionPane.showMessageDialog(null,"Não existe venda nesta data. \n " + erro);
       JOptionPane.showMessageDialog(null,"Não existe venda nesta data");
       ftxtvenda.requestFocus();
                     
        }           
    }//GEN-LAST:event_btnsair1ActionPerformed

    private void sttparcela5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sttparcela5KeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_sttparcela5KeyReleased

    private void sttparcela5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sttparcela5FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_sttparcela5FocusGained

    private void sttparcela4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sttparcela4KeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_sttparcela4KeyReleased

    private void sttparcela4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sttparcela4FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_sttparcela4FocusGained

    private void sttparcela3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sttparcela3KeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_sttparcela3KeyReleased

    private void sttparcela3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sttparcela3FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_sttparcela3FocusGained

    private void sttparcela2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sttparcela2KeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_sttparcela2KeyReleased

    private void sttparcela2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sttparcela2FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_sttparcela2FocusGained

    private void sttparcela1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sttparcela1KeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_sttparcela1KeyReleased

    private void sttparcela1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sttparcela1FocusGained
// TODO add your handling code here:
//        String nome = "Deseja alterar o status da parcela 1 ?";
//                int opcao_escolha = JOptionPane.showConfirmDialog(null,nome,"Alterar", JOptionPane.YES_NO_OPTION);
//                if(opcao_escolha==JOptionPane.YES_OPTION){
//                   btnalterar.requestFocus();
//                   sttparcela1.setText("PAGA");                   
//                }
//                if(opcao_escolha==JOptionPane.NO_OPTION){
//                        btnalterar.requestFocus();
//                       //  sttparcela1.setText("PAGA");   
//                }              
    }//GEN-LAST:event_sttparcela1FocusGained

    private void ftxtvencimento5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtvencimento5FocusLost
// TODO add your handling code here:
        Pattern p = Pattern
                .compile("^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$");
        Matcher m = p.matcher(ftxtvencimento5.getText());
        if (!m.find())
            
            JOptionPane.showMessageDialog(null, "Data inválida.");
    }//GEN-LAST:event_ftxtvencimento5FocusLost

    private void ftxtvencimento5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtvencimento5FocusGained
// TODO add your handling code here:
        ftxtvencimento5.selectAll();
    }//GEN-LAST:event_ftxtvencimento5FocusGained

    private void ftxtvencimento4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtvencimento4FocusLost
// TODO add your handling code here:
        Pattern p = Pattern
                .compile("^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$");
        Matcher m = p.matcher(ftxtvencimento4.getText());
        if (!m.find())
            
            JOptionPane.showMessageDialog(null, "Data inválida.");
    }//GEN-LAST:event_ftxtvencimento4FocusLost

    private void ftxtvencimento4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtvencimento4FocusGained
// TODO add your handling code here:
        ftxtvencimento4.selectAll();
    }//GEN-LAST:event_ftxtvencimento4FocusGained

    private void ftxtvencimento3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtvencimento3FocusLost
// TODO add your handling code here:
        Pattern p = Pattern
                .compile("^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$");
        Matcher m = p.matcher(ftxtvencimento3.getText());
        if (!m.find())
            
            JOptionPane.showMessageDialog(null, "Data inválida.");
    }//GEN-LAST:event_ftxtvencimento3FocusLost

    private void ftxtvencimento3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtvencimento3FocusGained
// TODO add your handling code here:
        ftxtvencimento3.selectAll();
    }//GEN-LAST:event_ftxtvencimento3FocusGained

    private void ftxtvencimento2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtvencimento2FocusLost
// TODO add your handling code here:
        Pattern p = Pattern
                .compile("^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$");
        Matcher m = p.matcher(ftxtvencimento2.getText());
        if (!m.find())
            
            JOptionPane.showMessageDialog(null, "Data inválida.");
    }//GEN-LAST:event_ftxtvencimento2FocusLost

    private void ftxtvencimento2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtvencimento2FocusGained
// TODO add your handling code here:
        ftxtvencimento2.selectAll();
    }//GEN-LAST:event_ftxtvencimento2FocusGained

    private void ftxtvencimento1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtvencimento1FocusLost
// TODO add your handling code here:
        Pattern p = Pattern
                .compile("^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$");
        Matcher m = p.matcher(ftxtvencimento1.getText());
        if (!m.find())
            
            JOptionPane.showMessageDialog(null, "Data inválida.");
    }//GEN-LAST:event_ftxtvencimento1FocusLost

    private void ftxtvencimento1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtvencimento1FocusGained
// TODO add your handling code here:
//        ftxtvencimento1.selectAll();
//        ftxtvencimento1.setText(ftxtdataentrada.getText());
//        ftxtvencimento2.setText(ftxtdataentrada.getText());
//        ftxtvencimento3.setText(ftxtdataentrada.getText());
//        ftxtvencimento4.setText(ftxtdataentrada.getText());
//        ftxtvencimento5.setText(ftxtdataentrada.getText());
    }//GEN-LAST:event_ftxtvencimento1FocusGained

    private void txtparcela5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtparcela5KeyReleased
// TODO add your handling code here:
        txtparcela5.setText(txtparcela5.getText().replace(",", ".")
        .replace("q", "").replace("w", "").replace("e", "")
        .replace("r", "").replace("t", "").replace("y", "")
        .replace("u", "").replace("i", "").replace("o", "")
        .replace("p", "").replace("´", "").replace("[", "")
        .replace("a", "").replace("s", "").replace("d", "")
        .replace("f", "").replace("g", "").replace("h", "")
        .replace("j", "").replace("k", "").replace("l", "")
        .replace("ç", "").replace("~", "").replace("]", "")
        .replace("|", "").replace("z", "").replace("x", "")
        .replace("c", "").replace("v", "").replace("b", "")
        .replace("n", "").replace("m", "").replace(";", "")
        .replace("<", "").replace(">", "").replace("/", "")
        .replace("^", "").replace("}", "").replace("º", "")
        .replace("{", "").replace("ª", "").replace("'", "")
        .replace("!", "").replace("@", "").replace("$", "")
        .replace("%", "").replace("¨", "").replace("&", "")
        .replace("*", "").replace("(", "").replace(")", "")
        .replace("+", "").replace("-", "").replace("_", "")
        .replace(")", "").replace("#", "").replace("?", "")
        .replace("°", ""));
    }//GEN-LAST:event_txtparcela5KeyReleased

    private void txtparcela5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtparcela5FocusGained
// TODO add your handling code here:
        txtparcela5.selectAll();
    }//GEN-LAST:event_txtparcela5FocusGained

    private void txtparcela4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtparcela4KeyReleased
// TODO add your handling code here:
        txtparcela4.setText(txtparcela4.getText().replace(",", ".")
        .replace("q", "").replace("w", "").replace("e", "")
        .replace("r", "").replace("t", "").replace("y", "")
        .replace("u", "").replace("i", "").replace("o", "")
        .replace("p", "").replace("´", "").replace("[", "")
        .replace("a", "").replace("s", "").replace("d", "")
        .replace("f", "").replace("g", "").replace("h", "")
        .replace("j", "").replace("k", "").replace("l", "")
        .replace("ç", "").replace("~", "").replace("]", "")
        .replace("|", "").replace("z", "").replace("x", "")
        .replace("c", "").replace("v", "").replace("b", "")
        .replace("n", "").replace("m", "").replace(";", "")
        .replace("<", "").replace(">", "").replace("/", "")
        .replace("^", "").replace("}", "").replace("º", "")
        .replace("{", "").replace("ª", "").replace("'", "")
        .replace("!", "").replace("@", "").replace("$", "")
        .replace("%", "").replace("¨", "").replace("&", "")
        .replace("*", "").replace("(", "").replace(")", "")
        .replace("+", "").replace("-", "").replace("_", "")
        .replace(")", "").replace("#", "").replace("?", "")
        .replace("°", ""));
    }//GEN-LAST:event_txtparcela4KeyReleased

    private void txtparcela4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtparcela4FocusGained
// TODO add your handling code here:
        txtparcela4.selectAll();
    }//GEN-LAST:event_txtparcela4FocusGained

    private void txtparcela3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtparcela3KeyReleased
// TODO add your handling code here:
        txtparcela3.setText(txtparcela3.getText().replace(",", ".")
        .replace("q", "").replace("w", "").replace("e", "")
        .replace("r", "").replace("t", "").replace("y", "")
        .replace("u", "").replace("i", "").replace("o", "")
        .replace("p", "").replace("´", "").replace("[", "")
        .replace("a", "").replace("s", "").replace("d", "")
        .replace("f", "").replace("g", "").replace("h", "")
        .replace("j", "").replace("k", "").replace("l", "")
        .replace("ç", "").replace("~", "").replace("]", "")
        .replace("|", "").replace("z", "").replace("x", "")
        .replace("c", "").replace("v", "").replace("b", "")
        .replace("n", "").replace("m", "").replace(";", "")
        .replace("<", "").replace(">", "").replace("/", "")
        .replace("^", "").replace("}", "").replace("º", "")
        .replace("{", "").replace("ª", "").replace("'", "")
        .replace("!", "").replace("@", "").replace("$", "")
        .replace("%", "").replace("¨", "").replace("&", "")
        .replace("*", "").replace("(", "").replace(")", "")
        .replace("+", "").replace("-", "").replace("_", "")
        .replace(")", "").replace("#", "").replace("?", "")
        .replace("°", ""));
    }//GEN-LAST:event_txtparcela3KeyReleased

    private void txtparcela3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtparcela3FocusGained
// TODO add your handling code here:
        txtparcela3.selectAll();
    }//GEN-LAST:event_txtparcela3FocusGained

    private void txtparcela2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtparcela2KeyReleased
// TODO add your handling code here:
        txtparcela2.setText(txtparcela2.getText().replace(",", ".")
        .replace("q", "").replace("w", "").replace("e", "")
        .replace("r", "").replace("t", "").replace("y", "")
        .replace("u", "").replace("i", "").replace("o", "")
        .replace("p", "").replace("´", "").replace("[", "")
        .replace("a", "").replace("s", "").replace("d", "")
        .replace("f", "").replace("g", "").replace("h", "")
        .replace("j", "").replace("k", "").replace("l", "")
        .replace("ç", "").replace("~", "").replace("]", "")
        .replace("|", "").replace("z", "").replace("x", "")
        .replace("c", "").replace("v", "").replace("b", "")
        .replace("n", "").replace("m", "").replace(";", "")
        .replace("<", "").replace(">", "").replace("/", "")
        .replace("^", "").replace("}", "").replace("º", "")
        .replace("{", "").replace("ª", "").replace("'", "")
        .replace("!", "").replace("@", "").replace("$", "")
        .replace("%", "").replace("¨", "").replace("&", "")
        .replace("*", "").replace("(", "").replace(")", "")
        .replace("+", "").replace("-", "").replace("_", "")
        .replace(")", "").replace("#", "").replace("?", "")
        .replace("°", ""));
    }//GEN-LAST:event_txtparcela2KeyReleased

    private void txtparcela2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtparcela2FocusGained
// TODO add your handling code here:
        txtparcela2.selectAll();
    }//GEN-LAST:event_txtparcela2FocusGained
public static String converterDoubleString(double precoDouble) {
        /*Transformando um double em 2 casas decimais*/
        DecimalFormat fmt = new DecimalFormat("0.00");    //limita o número de casas decimais
        String string = fmt.format(precoDouble);
        String[] part = string.split("[,]");
        String preco = part[0]+"."+part[1];
        return preco;
    }
    private void txtparcela1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtparcela1KeyReleased
// TODO add your handling code here:
        
        txtparcela1.setText(txtparcela1.getText().replace(",", ".")
        .replace("q", "").replace("w", "").replace("e", "")
        .replace("r", "").replace("t", "").replace("y", "")
        .replace("u", "").replace("i", "").replace("o", "")
        .replace("p", "").replace("´", "").replace("[", "")
        .replace("a", "").replace("s", "").replace("d", "")
        .replace("f", "").replace("g", "").replace("h", "")
        .replace("j", "").replace("k", "").replace("l", "")
        .replace("ç", "").replace("~", "").replace("]", "")
        .replace("|", "").replace("z", "").replace("x", "")
        .replace("c", "").replace("v", "").replace("b", "")
        .replace("n", "").replace("m", "").replace(";", "")
        .replace("<", "").replace(">", "").replace("/", "")
        .replace("^", "").replace("}", "").replace("º", "")
        .replace("{", "").replace("ª", "").replace("'", "")
        .replace("!", "").replace("@", "").replace("$", "")
        .replace("%", "").replace("¨", "").replace("&", "")
        .replace("*", "").replace("(", "").replace(")", "")
        .replace("+", "").replace("-", "").replace("_", "")
        .replace(")", "").replace("#", "").replace("?", "")
        .replace("°", ""));
    }//GEN-LAST:event_txtparcela1KeyReleased

    private void txtparcela1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtparcela1FocusGained
// TODO add your handling code here:
        txtparcela1.selectAll();
    }//GEN-LAST:event_txtparcela1FocusGained
    
    private void cmbnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnomeActionPerformed
// TODO add your handling code here:
        
        try {
            
            con_cliente.resultset.first();
            
            String igual = "n";
            while(igual == "n"){
                if(con_cliente.resultset.getString("nm_cliente").equals(cmbnome.getSelectedItem())){
                    igual = "s";
                } else
                    con_cliente.resultset.next();
            }
            txtcodigo.setText(con_cliente.resultset.getString(String.valueOf("cd_cliente")));
            mostraDados();
        } catch (SQLException ex) {
            ex.printStackTrace();
            
        }
   
    }//GEN-LAST:event_cmbnomeActionPerformed
    
    public void mostraDados(){
        
        
    }
    
    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed
    
    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
// TODO add your handling code here:
        cmbnome.setSelectedIndex(0);
        sttparcela1.setBackground(getBackground().white);
        sttparcela2.setBackground(getBackground().white);
        sttparcela3.setBackground(getBackground().white);
        sttparcela4.setBackground(getBackground().white);
        sttparcela5.setBackground(getBackground().white);
        txtobs.setBackground(getBackground().white);
        ftxtvencimento1.setText("");
        ftxtvencimento2.setText("");
        ftxtvencimento3.setText("");
        ftxtvencimento4.setText("");
        ftxtvencimento5.setText("");
        txtparcela1.setText("");
        txtparcela2.setText("");
        txtparcela3.setText("");
        txtparcela4.setText("");
        txtparcela5.setText("");
        sttparcela1.setText("");
        sttparcela2.setText("");
        sttparcela3.setText("");
        sttparcela4.setText("");
        sttparcela5.setText("");
        ftxtvenda.setText("");
        txtobs.setText("");
    }//GEN-LAST:event_btnlimparActionPerformed
        
    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        
        
        try {
            String sql = "UPDATE Contareceber1 Set ds_status1='"+sttparcela1.getText().toUpperCase()+"',"+
                    "ds_status2='"+sttparcela2.getText().toUpperCase()+"',"+
                    "ds_status3='"+sttparcela3.getText().toUpperCase()+"',"+
                    "ds_status4='"+sttparcela4.getText().toUpperCase()+"',"+
                    "ds_status5='"+sttparcela5.getText().toUpperCase()+"',"+
                    "ds_observacao='"+txtobs.getText().toUpperCase()+"' where cd_cliente ='"+txtcodigo.getText()+"'";
            con_receber.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!!!");
            
            //isso serve para atualizar o resultset
           con_receber.executeSQL("Select dt_vencimento1, dt_vencimento2, dt_vencimento3, dt_vencimento4, dt_vencimento5, vl_parcela1, vl_parcela2, vl_parcela3, vl_parcela4, vl_parcela5, ds_status1, ds_status2, ds_status3, ds_status4, ds_status5, ds_observacao FROM contareceber1 where cd_cliente='"
                    + txtcodigo.getText() + "'");
            con_receber.resultset.next();
           
           cmbnome.setSelectedIndex(0);
        sttparcela1.setBackground(getBackground().white);
        sttparcela2.setBackground(getBackground().white);
        sttparcela3.setBackground(getBackground().white);
        sttparcela4.setBackground(getBackground().white);
        sttparcela5.setBackground(getBackground().white);
        txtobs.setBackground(getBackground().white);
        ftxtvencimento1.setText("");
        ftxtvencimento2.setText("");
        ftxtvencimento3.setText("");
        ftxtvencimento4.setText("");
        ftxtvencimento5.setText("");
        txtparcela1.setText("");
        txtparcela2.setText("");
        txtparcela3.setText("");
        txtparcela4.setText("");
        txtparcela5.setText("");
        sttparcela1.setText("");
        sttparcela2.setText("");
        sttparcela3.setText("");
        sttparcela4.setText("");
        sttparcela5.setText("");
        ftxtvenda.setText("");
        txtobs.setText("");
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnalterarActionPerformed
                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaReceberCliente().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnalterar;
    private java.awt.Button btnlimpar;
    private java.awt.Button btnsair;
    private java.awt.Button btnsair1;
    private javax.swing.JComboBox cmbnome;
    private javax.swing.JFormattedTextField ftxtvencimento1;
    private javax.swing.JFormattedTextField ftxtvencimento2;
    private javax.swing.JFormattedTextField ftxtvencimento3;
    private javax.swing.JFormattedTextField ftxtvencimento4;
    private javax.swing.JFormattedTextField ftxtvencimento5;
    private javax.swing.JFormattedTextField ftxtvenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField sttparcela1;
    private javax.swing.JTextField sttparcela2;
    private javax.swing.JTextField sttparcela3;
    private javax.swing.JTextField sttparcela4;
    private javax.swing.JTextField sttparcela5;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextArea txtobs;
    private javax.swing.JTextField txtparcela1;
    private javax.swing.JTextField txtparcela2;
    private javax.swing.JTextField txtparcela3;
    private javax.swing.JTextField txtparcela4;
    private javax.swing.JTextField txtparcela5;
    // End of variables declaration//GEN-END:variables
    
}
