/*
 * ConsultaAniversario.java
 *
 * Created on 6 de Setembro de 2011, 13:30
 */

package View;

import Controle.conexao;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Relatorio.*;

/**
 *
 * @author  Familia-Silva
 */
public class ConsultaAniversario extends javax.swing.JFrame {
    private conexao con_cliente, con_endereco, con_telefone, con_email;
    private int numeroRegistros = 1;
    
    /** Creates new form ConsultaAniversario */
    public ConsultaAniversario() {
        initComponents();
         setResizable(false);
        con_cliente=new conexao();
        con_cliente.conecta();
        
preenchejTabla();
        enter();
        Runtime rt = Runtime.getRuntime();
		int MB = 1048576; // total de bytes em 1MB

		double total = rt.maxMemory() / MB;
		double inicio = total - (carregarMemoria()/MB);
		
		//System.out.println(total);
		//System.out.println(inicio);
		
		// Metodo de limpaza
		rt.runFinalization();
		rt.gc();
		
		double fim = total - rt.freeMemory()/ MB;
		System.out.println("Início = " +inicio + "Fim = " + fim);
    }
 public void enter(){
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        consulta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdbnome = new javax.swing.JRadioButton();
        rdbperiodo = new javax.swing.JRadioButton();
        cmbmes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnconsulta = new javax.swing.JButton();
        btnconsulta1 = new javax.swing.JButton();
        btnconsulta2 = new javax.swing.JButton();
        btnconsulta3 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Anivers\u00e1rio");
        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Consulta"));
        consulta.add(rdbnome);
        rdbnome.setText("Nome");
        rdbnome.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdbnome.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdbnome.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbnomeItemStateChanged(evt);
            }
        });

        jPanel1.add(rdbnome);
        rdbnome.setBounds(10, 30, 70, 15);

        consulta.add(rdbperiodo);
        rdbperiodo.setText("Per\u00edodo");
        rdbperiodo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdbperiodo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rdbperiodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbperiodoItemStateChanged(evt);
            }
        });

        jPanel1.add(rdbperiodo);
        rdbperiodo.setBounds(10, 60, 70, 15);

        cmbmes.setMaximumRowCount(5);
        cmbmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cmbmes.setEnabled(false);
        jPanel1.add(cmbmes);
        cmbmes.setBounds(90, 50, 56, 20);

        jLabel1.setText("M\u00eas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 30, 40, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 160, 90);

        txtnome.setEnabled(false);
        getContentPane().add(txtnome);
        txtnome.setBounds(10, 130, 280, 20);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 70, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Nome", "Dia ", "Mês", "Tel1.", "Tel2.", "Email", "Logradouro", "N°", "Cep", "Cidade"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 610, 180);

        btnconsulta.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnconsulta.setText("Consulta");
        btnconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaActionPerformed(evt);
            }
        });

        getContentPane().add(btnconsulta);
        btnconsulta.setBounds(10, 350, 90, 30);

        btnconsulta1.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnconsulta1.setText("Limpar");
        btnconsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsulta1ActionPerformed(evt);
            }
        });

        getContentPane().add(btnconsulta1);
        btnconsulta1.setBounds(210, 350, 90, 30);

        btnconsulta2.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnconsulta2.setText("Sair");
        btnconsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsulta2ActionPerformed(evt);
            }
        });

        getContentPane().add(btnconsulta2);
        btnconsulta2.setBounds(310, 350, 90, 30);

        btnconsulta3.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnconsulta3.setText("Imprimir");
        btnconsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsulta3ActionPerformed(evt);
            }
        });

        getContentPane().add(btnconsulta3);
        btnconsulta3.setBounds(110, 350, 90, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-645)/2, (screenSize.height-423)/2, 645, 423);
    }// </editor-fold>//GEN-END:initComponents
private void consultaPeriodo(){
        con_cliente.executeSQL("Select c.nm_cliente, dt_dia_nascimento,dt_mes_nascimento,t.cd_tel1, t.cd_tel2, e.nm_email1, en.nm_logradouro, en.cd_numero, en.cd_cep,en.nm_cidade  FROM Cliente c Left Join Telefone t ON (c.cd_cliente=t.cd_cliente) left join email e on (c.cd_cliente=e.cd_cliente) left join endereco en on (c.cd_cliente=en.cd_cliente) where dt_mes_nascimento = '"
                + cmbmes.getSelectedItem() + "' order by dt_dia_nascimento");
        preenchejTabla1();
    }
    private void consultaNome(){
        con_cliente.executeSQL("Select c.nm_cliente, dt_dia_nascimento,dt_mes_nascimento, t.cd_tel1, t.cd_tel2, e.nm_email1, en.nm_logradouro, en.cd_numero, en.cd_cep,en.nm_cidade  FROM Cliente c Left Join Telefone t ON (c.cd_cliente=t.cd_cliente) left join email e on (c.cd_cliente=e.cd_cliente) left join endereco en on (c.cd_cliente=en.cd_cliente) where nm_cliente LIKE  '"
                + txtnome.getText().toUpperCase() + "%' order by dt_dia_nascimento");
        preenchejTabla1();
    }
    private void btnconsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsulta3ActionPerformed
// TODO add your handling code here:
        if((rdbperiodo.isSelected()== true) && (cmbmes.getSelectedItem().equals("-"))){
            JOptionPane.showMessageDialog(null,"Selecione um mês.");
        }
        if((rdbperiodo.isSelected()== true) && (!cmbmes.getSelectedItem().equals("-"))){
            
            new Rel_Aniversariante();
            ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
        jTable1.updateUI();
        txtnome.setText("");
        txtnome.setEnabled(false);
        consulta.clearSelection();
        cmbmes.setSelectedIndex(0);
        cmbmes.setEnabled(false);
        }
        
        if(rdbnome.isSelected()){
            new Rel_Aniversariante_nome();
            ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
        jTable1.updateUI();
        txtnome.setText("");
        txtnome.setEnabled(false);
        consulta.clearSelection();
        cmbmes.setSelectedIndex(0);
        cmbmes.setEnabled(false);
        }
    }//GEN-LAST:event_btnconsulta3ActionPerformed

    private void btnconsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsulta2ActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnconsulta2ActionPerformed
 public static long carregarMemoria(){
		
		ArrayList<Integer> list = new ArrayList<Integer>();
		for(int i = 0; i<1000000; i++){
		list.add(i);	
		}
		return Runtime.getRuntime().freeMemory();
	}   
    private void btnconsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsulta1ActionPerformed
// TODO add your handling code here:
        ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
        jTable1.updateUI();
        txtnome.setText("");
        consulta.clearSelection();
        cmbmes.setSelectedIndex(0);
        cmbmes.setEnabled(false);
    }//GEN-LAST:event_btnconsulta1ActionPerformed
    
    private void btnconsultaActionPerformed(java.awt.event.ActionEvent evt) {
         final DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        
        if((rdbnome.isSelected()== false) && (rdbperiodo.isSelected()== false)){
            JOptionPane.showMessageDialog(null,"Selecione um tipo de consulta.");
        }
        if((rdbperiodo.isSelected()== true) && (cmbmes.getSelectedItem().equals("-"))){
            JOptionPane.showMessageDialog(null,"Selecione um mês.");
        }
        if((rdbnome.isSelected()== true) && (txtnome.getText().equals(""))){
            
            JOptionPane.showMessageDialog(null,"Digite uma letra ou um nome.");
             
           
            ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
             jTable1.updateUI();
            txtnome.requestFocus();
         
        }
        else if(rdbnome.isSelected()){
            consultaNome();
        }
        if(rdbperiodo.isSelected()){
            consultaPeriodo();
        }
        
    }
    
    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained
    
    private void rdbperiodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbperiodoItemStateChanged
// TODO add your handling code here:
        if(rdbperiodo.isSelected()){
            txtnome.setEnabled(false);
            cmbmes.setEnabled(true);
            cmbmes.requestFocus();
            txtnome.setText("");
            
        }
    }//GEN-LAST:event_rdbperiodoItemStateChanged
    public void preenchejTabla(){
    final DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(100);    
    }
    public void preenchejTabla1(){
        final DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(100);  
        
        modelo.setNumRows(0);
        numeroRegistros=1;
        
        try{
            while (con_cliente.resultset.next())
                modelo.addRow(new Object []{numeroRegistros++,con_cliente.resultset.getString("nm_cliente"), con_cliente.resultset.getString("dt_dia_nascimento"),con_cliente.resultset.getString("dt_mes_nascimento"), con_cliente.resultset.getString("cd_tel1"),con_cliente.resultset.getString("cd_tel2"),
                con_cliente.resultset.getString("nm_email1"),con_cliente.resultset.getString("nm_logradouro"),con_cliente.resultset.getString("cd_numero"),con_cliente.resultset.getString("cd_cep"), con_cliente.resultset.getString("nm_cidade")});
            
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }//Essas duas linhas é necesária
    }
    private void rdbnomeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbnomeItemStateChanged
// TODO add your handling code here:
        if(rdbnome.isSelected()){
            txtnome.setEnabled(true);
            txtnome.requestFocus();
            cmbmes.setEnabled(false);
            
        }
    }//GEN-LAST:event_rdbnomeItemStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAniversario().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsulta;
    private javax.swing.JButton btnconsulta1;
    private javax.swing.JButton btnconsulta2;
    private javax.swing.JButton btnconsulta3;
    public static javax.swing.JComboBox cmbmes;
    private javax.swing.ButtonGroup consulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdbnome;
    private javax.swing.JRadioButton rdbperiodo;
    public static javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
    
}
