/*
 * ConsultaMateriaPrima.java
 *
 * Created on 7 de Setembro de 2011, 15:33
 */

package View;
import Controle.conexao;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author  Familia-Silva
 */
public class ConsultaMateriaPrima extends javax.swing.JFrame {
    private conexao con_produto, con_cor,con_saldo, con_aviamento,con_produtoacbado1,con_produtoacbado2,con_produtoacbado3,con_produtoacbado4,con_produtoacbado,con_produtoacbado5,con_produtoacbado6;
    private int numeroRegistros = 1;
    private int iniciacombo=0;
    /** Creates new form ConsultaMateriaPrima */
    public ConsultaMateriaPrima() {
        initComponents();
        preenchejTable();
        con_saldo = new conexao();
        con_saldo.conecta();
        setResizable(false);
        cmbproduto.setVisible(false);
        cmbaviamento.setVisible(false);
        con_produto=new conexao();
        con_produto.conecta();
        con_cor=new conexao();
        con_cor.conecta();
        con_aviamento=new conexao();
        con_aviamento.conecta();
        con_produtoacbado1 = new conexao();
        con_produtoacbado1.conecta();
        con_produtoacbado = new conexao();
        con_produtoacbado.conecta();
        
        con_cor.executeSQL("select * from cor order by nm_cor");
        con_produto.executeSQL("select * from Tecido order by nm_tecido");
        con_aviamento.executeSQL("select * from Aviamento order by nm_aviamento");
        try {
            
            while(con_cor.resultset.next())
                cmbcor.addItem(con_cor.resultset.getString("nm_cor"));
            while(con_produto.resultset.next())
                cmbproduto.addItem(con_produto.resultset.getString("nm_tecido"));
            while(con_aviamento.resultset.next())
                cmbaviamento.addItem(con_aviamento.resultset.getString("nm_aviamento"));
            
        } catch(SQLException erro) {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }
        enter();
        Runtime rt = Runtime.getRuntime();
		int MB = 1048576; // total de bytes em 1MB

		double total = rt.maxMemory() / MB;
		double inicio = total - (carregarMemoria()/MB);
		
		//System.out.println(total);
		//System.out.println(inicio);
		
		// Metodo de limpaza
		rt.runFinalization();
		rt.gc();
		
		double fim = total - rt.freeMemory()/ MB;
		System.out.println("Início = " +inicio + "Fim = " + fim);
    }
    public void enter(){
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnconsulta = new javax.swing.JButton();
        btnconsulta1 = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbproduto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbcor = new javax.swing.JComboBox();
        cmbtipo = new javax.swing.JComboBox();
        cmbtamanho = new javax.swing.JComboBox();
        lblcodcor = new javax.swing.JLabel();
        lblcodproduto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblpeca = new javax.swing.JLabel();
        lblmetro = new javax.swing.JLabel();
        lblkilo = new javax.swing.JLabel();
        cmbaviamento = new javax.swing.JComboBox();
        cmbcontrole = new javax.swing.JComboBox();
        lblcodaviamento = new javax.swing.JLabel();
        lbltamanho = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Saldo Mt\u00e9ria Prima");
        btnconsulta.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnconsulta.setText("Consulta");
        btnconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaActionPerformed(evt);
            }
        });

        getContentPane().add(btnconsulta);
        btnconsulta.setBounds(10, 260, 90, 30);

        btnconsulta1.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnconsulta1.setText("Limpar");
        btnconsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsulta1ActionPerformed(evt);
            }
        });

        getContentPane().add(btnconsulta1);
        btnconsulta1.setBounds(110, 260, 90, 30);

        btnsair.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnsair.setText("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        getContentPane().add(btnsair);
        btnsair.setBounds(210, 260, 90, 30);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Produto", "Cor", "Tamanho", "Metro", "Kilo", "Peça"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 720, 180);

        cmbproduto.setMaximumRowCount(5);
        cmbproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprodutoActionPerformed(evt);
            }
        });

        getContentPane().add(cmbproduto);
        cmbproduto.setBounds(120, 30, 200, 20);

        jLabel1.setText("Produto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 60, 14);

        jLabel2.setText("Cor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 10, 60, 14);

        cmbcor.setMaximumRowCount(5);
        cmbcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcorActionPerformed(evt);
            }
        });

        getContentPane().add(cmbcor);
        cmbcor.setBounds(330, 30, 280, 20);

        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "AVIAMENTO", "TECIDO" }));
        cmbtipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbtipoItemStateChanged(evt);
            }
        });
        cmbtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipoActionPerformed(evt);
            }
        });

        getContentPane().add(cmbtipo);
        cmbtipo.setBounds(10, 30, 100, 20);

        cmbtamanho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "PEQUENO", "MEDIO", "GRANDE" }));
        cmbtamanho.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbtamanhoItemStateChanged(evt);
            }
        });
        cmbtamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtamanhoActionPerformed(evt);
            }
        });

        getContentPane().add(cmbtamanho);
        cmbtamanho.setBounds(620, 30, 100, 20);

        lblcodcor.setText("Cor");
        getContentPane().add(lblcodcor);
        lblcodcor.setBounds(360, 30, 60, 14);

        lblcodproduto.setText("Produto");
        getContentPane().add(lblcodproduto);
        lblcodproduto.setBounds(370, 30, 60, 14);

        jLabel3.setText("Tipo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 60, 14);

        lblpeca.setText("0");
        getContentPane().add(lblpeca);
        lblpeca.setBounds(640, 30, 60, 14);

        lblmetro.setText("0.00");
        getContentPane().add(lblmetro);
        lblmetro.setBounds(630, 30, 60, 14);

        lblkilo.setText("0.00");
        getContentPane().add(lblkilo);
        lblkilo.setBounds(640, 30, 30, 14);

        cmbaviamento.setMaximumRowCount(5);
        cmbaviamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbaviamentoActionPerformed(evt);
            }
        });

        getContentPane().add(cmbaviamento);
        cmbaviamento.setBounds(120, 30, 200, 20);

        cmbcontrole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cmbcontrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcontroleActionPerformed(evt);
            }
        });

        getContentPane().add(cmbcontrole);
        cmbcontrole.setBounds(120, 30, 200, 20);

        lblcodaviamento.setText("aviamento");
        getContentPane().add(lblcodaviamento);
        lblcodaviamento.setBounds(40, 30, 50, 14);

        lbltamanho.setText("1");
        getContentPane().add(lbltamanho);
        lbltamanho.setBounds(360, 30, 60, 14);

        jLabel4.setText("Tamanho");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 10, 60, 14);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-749)/2, (screenSize.height-335)/2, 749, 335);
    }// </editor-fold>//GEN-END:initComponents
    
    private void cmbtamanhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbtamanhoItemStateChanged
// TODO add your handling code here:
        
        
    }//GEN-LAST:event_cmbtamanhoItemStateChanged
   public static long carregarMemoria(){
		
		ArrayList<Integer> list = new ArrayList<Integer>();
		for(int i = 0; i<1000000; i++){
		list.add(i);	
		}
		return Runtime.getRuntime().freeMemory();
	}     
    private void cmbcontroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcontroleActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_cmbcontroleActionPerformed
    
    private void cmbaviamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbaviamentoActionPerformed
// TODO add your handling code here:
        if(iniciacombo == 1){
            try {
                
                con_aviamento.resultset.first();
                String igual = "n";
                while(igual == "n"){
                    if(con_aviamento.resultset.getString("nm_aviamento").equals(cmbaviamento.getSelectedItem())){
                        igual = "s";
                    } else
                        con_aviamento.resultset.next();
                }
                lblcodaviamento.setText(con_aviamento.resultset.getString(String.valueOf("cd_aviamento")));
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                
            }
        }
        iniciacombo=1;
    }//GEN-LAST:event_cmbaviamentoActionPerformed
    
    private void cmbtipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbtipoItemStateChanged
// TODO add your handling code here:
        if(cmbtipo.getSelectedItem().equals("AVIAMENTO")){
            cmbproduto.setVisible(false);
            cmbproduto.setSelectedIndex(0);
            cmbaviamento.setVisible(true);
            
        }
        if(cmbtipo.getSelectedItem().equals("TECIDO")){
            cmbproduto.setVisible(true);
            cmbaviamento.setVisible(false);
            cmbaviamento.setSelectedIndex(0);
            lblpeca.setText("0");
        }
        if(cmbtipo.getSelectedItem().equals("-")){
            cmbproduto.setVisible(false);
            cmbproduto.setSelectedIndex(0);
            cmbaviamento.setVisible(false);
            cmbaviamento.setSelectedIndex(0);
            cmbcontrole.setVisible(true);
            
        }
    }//GEN-LAST:event_cmbtipoItemStateChanged
    
    private void cmbtamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtamanhoActionPerformed
// TODO add your handling code here:
        if(cmbtamanho.getSelectedItem().equals("-")){
            lbltamanho.setText("0");
        }
        if(!cmbtamanho.getSelectedItem().equals("-")){
            lbltamanho.setText("1");
        }
    }//GEN-LAST:event_cmbtamanhoActionPerformed
    
    private void cmbtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipoActionPerformed
// TODO add your handling code here:
        if(cmbtipo.getSelectedItem().equals("TECIDO")){
            cmbtamanho.setEnabled(false);
        }
    }//GEN-LAST:event_cmbtipoActionPerformed
    
    private void cmbcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcorActionPerformed
// TODO add your handling code here:
        
        if(iniciacombo == 1){
            try {
                
                con_cor.resultset.first();
                String igual = "n";
                while(igual == "n"){
                    if(con_cor.resultset.getString("nm_cor").equals(cmbcor.getSelectedItem())){
                        igual = "s";
                    } else
                        con_cor.resultset.next();
                }
                lblcodcor.setText(con_cor.resultset.getString(String.valueOf("cd_cor")));
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                
            }
        }
        iniciacombo=1;
    }//GEN-LAST:event_cmbcorActionPerformed
    
    private void cmbprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprodutoActionPerformed
// TODO add your handling code here:
        if(iniciacombo == 1){
            try {
                
                con_produto.resultset.first();
                String igual = "n";
                while(igual == "n"){
                    if(con_produto.resultset.getString("nm_tecido").equals(cmbproduto.getSelectedItem())){
                        igual = "s";
                    } else
                        con_produto.resultset.next();
                }
                lblcodproduto.setText(con_produto.resultset.getString(String.valueOf("cd_tecido")));
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                
            }
        }
        iniciacombo=1;
    }//GEN-LAST:event_cmbprodutoActionPerformed
    
    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained
    
    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed
    
    private void btnconsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsulta1ActionPerformed
// TODO add your handling code here:
        
        
        
        ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
        jTable1.updateUI();
        numeroRegistros = 1;
        cmbproduto.setSelectedIndex(0);
        cmbcor.setSelectedIndex(0);
        cmbtipo.setSelectedIndex(0);
        cmbtamanho.setSelectedIndex(0);
    }//GEN-LAST:event_btnconsulta1ActionPerformed
    public void preenchejTable(){
        final DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(62);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(62);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(62);
    }
    public void preenchejTablaAviamento(){
        final DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(62);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(62);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(62);
        
        // modelo.setNumRows(0);
        // numeroRegistros=1;
        con_produtoacbado1 = new conexao();
        con_produtoacbado1.conecta();
        
        
        
        try {
            con_saldo.executeSQL("SELECT qt_metro, qt_peca FROM Saldomateriaprima where cd_aviamento='"
                    + Integer.parseInt(lblcodaviamento.getText())
                    + "' and cd_cor = '"
                    + Integer.parseInt(lblcodcor.getText())
                    + "' and nm_tamanho = '"
                    + cmbtamanho.getSelectedItem() + "'");
            
            con_saldo.resultset.first();
            
            lblmetro.setText(converterDoubleString(con_saldo.resultset.getDouble("qt_metro")));
            lblpeca.setText(converterDoubleString(con_saldo.resultset.getDouble("qt_peca")));
            
            modelo.addRow(new Object []{numeroRegistros++,cmbaviamento.getSelectedItem(), cmbcor.getSelectedItem(),cmbtamanho.getSelectedItem(),lblmetro.getText(),lblkilo.getText(),lblpeca.getText()});
       } catch(SQLException erro) {
            JOptionPane.showMessageDialog(null,"Combinação não localizada");
        }
    }
    public void preenchejTablaTecido(){
        final DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
       jTable1.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(62);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(62);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(62);
        
        
        // modelo.setNumRows(0);
        // numeroRegistros=1;
        con_produtoacbado1 = new conexao();
        con_produtoacbado1.conecta();
        
        
        
        try {
           con_saldo.executeSQL("SELECT qt_metro, qt_kilo FROM Saldomateriaprima where cd_tecido='"
                        + Integer.parseInt(lblcodproduto.getText())
                        + "' and cd_cor = '"
                        + Integer.parseInt(lblcodcor.getText())
                        + "'");
                
                con_saldo.resultset.first();
                
              
                lblkilo.setText(converterDoubleString(con_saldo.resultset.getDouble("qt_kilo")));
                lblmetro.setText(converterDoubleString(con_saldo.resultset.getDouble("qt_metro")));
         modelo.addRow(new Object []{numeroRegistros++,cmbproduto.getSelectedItem(), cmbcor.getSelectedItem(),"-",lblmetro.getText(),lblkilo.getText(),lblpeca.getText()});
                // modelo.addRow(new Object []{numeroRegistros++,cmbaviamento.getSelectedItem(), cmbcor.getSelectedItem(),cmbtamanho.getSelectedItem(),lblmetro.getText(),"0.00","0"});
        } catch(SQLException erro) {
            JOptionPane.showMessageDialog(null,"Combinação não localizada");
        }
        
       
        
        
    }
     public static String converterDoubleString(double precoDouble) {  
   /*Transformando um double em 2 casas decimais*/  
   DecimalFormat fmt = new DecimalFormat("0.00");    //limita o número de casas decimais     
   String string = fmt.format(precoDouble);  
   String[] part = string.split("[,]");  
   String preco = part[0]+"."+part[1];  
   return preco;  
}  
    private void btnconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaActionPerformed
// TODO add your handling code here:
        if(cmbtipo.getSelectedItem().equals("AVIAMENTO")&&lbltamanho.getText().equals("1")){
            preenchejTablaAviamento();
            // preenchejTablaApeca();
        }
        if(cmbtipo.getSelectedItem().equals("TECIDO")){
            
            preenchejTablaTecido();
            
            // preenchejTablaApeca();
        }
    }//GEN-LAST:event_btnconsultaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaMateriaPrima().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsulta;
    private javax.swing.JButton btnconsulta1;
    private javax.swing.JButton btnsair;
    private javax.swing.JComboBox cmbaviamento;
    private javax.swing.JComboBox cmbcontrole;
    private javax.swing.JComboBox cmbcor;
    private javax.swing.JComboBox cmbproduto;
    private javax.swing.JComboBox cmbtamanho;
    private javax.swing.JComboBox cmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcodaviamento;
    private javax.swing.JLabel lblcodcor;
    private javax.swing.JLabel lblcodproduto;
    private javax.swing.JLabel lblkilo;
    private javax.swing.JLabel lblmetro;
    private javax.swing.JLabel lblpeca;
    private javax.swing.JLabel lbltamanho;
    // End of variables declaration//GEN-END:variables
    
}
