/*
 * ConsultaProdutoAcabado.java
 *
 * Created on 7 de Setembro de 2011, 11:55
 */

package View;

import Controle.conexao;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Familia-Silva
 */
public class ConsultaProdutoAcabado extends javax.swing.JFrame {
    private conexao con_produto, con_cor, con_cliente,con_telefone, con_email,con_produtoacbado1,con_produtoacbado2,con_produtoacbado3,con_produtoacbado4,con_produtoacbado,con_produtoacbado5,con_produtoacbado6;
    private int numeroRegistros = 1;
    private int iniciacombo=0;
    /** Creates new form ConsultaProdutoAcabado */
    public ConsultaProdutoAcabado() {
        initComponents();
        con_produto=new conexao();
        con_produto.conecta();
        con_cor=new conexao();
        con_cor.conecta();
        preencheTabela();
        enter();
        setResizable(false);
        con_cor.executeSQL("select * from cor order by nm_cor");
        con_produto.executeSQL("select * from produto order by nm_produto");
        try {
            
              while(con_produto.resultset.next())
                cmbproduto.addItem(con_produto.resultset.getString("nm_produto"));
            
        } catch(SQLException erro) {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }
        Runtime rt = Runtime.getRuntime();
		int MB = 1048576; // total de bytes em 1MB

		double total = rt.maxMemory() / MB;
		double inicio = total - (carregarMemoria()/MB);
		
		//System.out.println(total);
		//System.out.println(inicio);
		
		// Metodo de limpaza
		rt.runFinalization();
		rt.gc();
		
		double fim = total - rt.freeMemory()/ MB;
		System.out.println("Início = " +inicio + "Fim = " + fim);
    }
    public void enter(){
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }
     public static long carregarMemoria(){
		
		ArrayList<Integer> list = new ArrayList<Integer>();
		for(int i = 0; i<1000000; i++){
		list.add(i);	
		}
		return Runtime.getRuntime().freeMemory();
	}   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        cmbproduto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblcodproduto = new javax.swing.JLabel();
        btnconsulta = new javax.swing.JButton();
        btnconsulta1 = new javax.swing.JButton();
        btnconsulta2 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Produto Acabado");
        cmbproduto.setMaximumRowCount(5);
        cmbproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprodutoActionPerformed(evt);
            }
        });

        getContentPane().add(cmbproduto);
        cmbproduto.setBounds(20, 30, 250, 20);

        jLabel1.setText("Produto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 60, 14);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Produto", "Cor", "P", "M", "G", "GG", "EG", "EXG"
            }
        ));
        jTable1.setAutoCreateColumnsFromModel(false);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 70, 610, 180);

        lblcodproduto.setText("Produto");
        getContentPane().add(lblcodproduto);
        lblcodproduto.setBounds(70, 30, 60, 14);

        btnconsulta.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnconsulta.setText("Consulta");
        btnconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaActionPerformed(evt);
            }
        });

        getContentPane().add(btnconsulta);
        btnconsulta.setBounds(10, 260, 90, 30);

        btnconsulta1.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnconsulta1.setText("Limpar");
        btnconsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsulta1ActionPerformed(evt);
            }
        });

        getContentPane().add(btnconsulta1);
        btnconsulta1.setBounds(110, 260, 90, 30);

        btnconsulta2.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnconsulta2.setText("Sair");
        btnconsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsulta2ActionPerformed(evt);
            }
        });

        getContentPane().add(btnconsulta2);
        btnconsulta2.setBounds(210, 260, 90, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-634)/2, (screenSize.height-335)/2, 634, 335);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnconsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsulta2ActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnconsulta2ActionPerformed
    public void preencheTabela(){
        final DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(40);
        
        modelo.setNumRows(0);
        numeroRegistros=1;
    }
    private void btnconsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsulta1ActionPerformed
// TODO add your handling code here:
        ((DefaultTableModel) jTable1.getModel()).setNumRows(0);
        jTable1.updateUI();
        numeroRegistros = 1;
        cmbproduto.setSelectedIndex(0);
                
    }//GEN-LAST:event_btnconsulta1ActionPerformed
    
    private void btnconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaActionPerformed
// TODO add your handling code here:
        preenchejTabla1();
       
        cmbproduto.setSelectedIndex(0);
      
    }//GEN-LAST:event_btnconsultaActionPerformed
        
    private void cmbprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprodutoActionPerformed
// TODO add your handling code here:
        if(iniciacombo == 1){
            try {
                
                con_produto.resultset.first();
                String igual = "n";
                while(igual == "n"){
                    if(con_produto.resultset.getString("nm_produto").equals(cmbproduto.getSelectedItem())){
                        igual = "s";
                    } else
                        con_produto.resultset.next();
                }
                lblcodproduto.setText(con_produto.resultset.getString(String.valueOf("cd_produto")));
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                
            }
        }
        iniciacombo=1;
    }//GEN-LAST:event_cmbprodutoActionPerformed
    public void preenchejTabla1(){
        final DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(40);
        
        // modelo.setNumRows(0);
        // numeroRegistros=1;
        con_produtoacbado1 = new conexao();
        con_produtoacbado1.conecta();
        
        con_produtoacbado2 = new conexao();
        con_produtoacbado2.conecta();
        
        con_produtoacbado3 = new conexao();
        con_produtoacbado3.conecta();
        
        con_produtoacbado4 = new conexao();
        con_produtoacbado4.conecta();
        
        con_cliente = new conexao();
        con_cliente.conecta();
        
        try {
            con_cliente= new conexao();
            con_cliente.conecta();
            con_cliente.executeSQL("Select  a.nm_produto, cc.nm_cor, m.qt_p, m.qt_m, m.qt_g, m.qt_gg, m.qt_eg, m.qt_exg FROM produtoacabado as m natural join cor  as cc natural join produto as a where cd_produto = '"
                    +lblcodproduto.getText()+ "' order by nm_cor");
            
            while(con_cliente.resultset.next())
                
             modelo.addRow(new Object []{numeroRegistros++, con_cliente.resultset.getString("nm_produto"),con_cliente.resultset.getString("nm_cor"),con_cliente.resultset.getInt("qt_p"),con_cliente.resultset.getInt("qt_m"),con_cliente.resultset.getInt("qt_g"),con_cliente.resultset.getInt("qt_gg"),con_cliente.resultset.getInt("qt_eg"),con_cliente.resultset.getInt("qt_exg")});
                
            
        } catch(SQLException erro) {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }
     
//
//
//
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }//Essas duas linhas é necesária
    }
    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaProdutoAcabado().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsulta;
    private javax.swing.JButton btnconsulta1;
    private javax.swing.JButton btnconsulta2;
    private javax.swing.JComboBox cmbproduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcodproduto;
    // End of variables declaration//GEN-END:variables
    
}
