/*
 * EntradaProdutoAcabadoDireto.java
 *
 * Created on 15 de Setembro de 2011, 09:30
 */

package View;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import Controle.*;
import Modelo.*;
import org.lavieri.modelutil.cep.WebServiceCep;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.MaskFormatter;
import Controle.*;
import Modelo.*;
/**
 *
 * @author  Familia-Silva
 */
public class EntradaProdutoAcabadoDireto extends javax.swing.JFrame {
    private conexao con_fechamento, con_terceirizada, con_cor, con_produto, con_saldo, con_produtoacbado,con_produtoacbado1,con_produtoacbado2,con_produtoacbado3,con_produtoacbado4,con_produtoacbado5,con_produtoacbado6;
    private int iniciacombo=0;
    private int qtdestoquetinhap=0;
    private int qtdestoquetinham=0;
    private int qtdestoquetinhag=0;
    private int qtdestoquetinhagg=0;
    private int qtdestoquetinhaeg=0;
    private int qtdestoquetinhaexg=0;
    /** Creates new form EntradaProdutoAcabadoDireto */
    public EntradaProdutoAcabadoDireto() {
        initComponents();
       lblcodcor.setVisible(false);
       lblcodproduto.setVisible(false);
        con_saldo = new conexao();
        con_saldo.conecta();
        
        con_fechamento = new conexao();
        con_fechamento.conecta();
        
        con_produto= new conexao();
        con_produto.conecta();
        
        con_cor = new conexao();
        con_cor.conecta();
        
        con_terceirizada = new conexao();
        con_terceirizada.conecta();
        
        con_produtoacbado6 = new conexao();
        con_produtoacbado6.conecta();
        setResizable(false);
        con_produto = new conexao();
        con_produto.conecta();
        con_cor= new conexao();
        con_cor.conecta();
        
        con_produto.executeSQL("SELECT * FROM produto order by nm_produto");
        con_cor.executeSQL("SELECT * FROM cor order by nm_cor");
        con_produtoacbado6.executeSQL("SELECT * FROM produtoacabado order by cd_produto");
        con_fechamento.executeSQL("Select  f.*, t.nm_contato, c.cd_cor, c.nm_cor,p.nm_produto FROM fechprod as f natural join Terceirizada as t natural join Cor  as c natural join Produto as p order by cd_numlote");
        
        try {
            while(con_produto.resultset.next())
                cmbproduto.addItem(con_produto.resultset.getString("nm_produto"));
            while(con_cor.resultset.next())
                cmbcor.addItem(con_cor.resultset.getString("nm_cor"));
            
        } catch(SQLException erro) {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }
        enter();
        zerar();
        Runtime rt = Runtime.getRuntime();
		int MB = 1048576; // total de bytes em 1MB

		double total = rt.maxMemory() / MB;
		double inicio = total - (carregarMemoria()/MB);
		
		//System.out.println(total);
		//System.out.println(inicio);
		
		// Metodo de limpaza
		rt.runFinalization();
		rt.gc();
		
		double fim = total - rt.freeMemory()/ MB;
		System.out.println("Início = " +inicio + "Fim = " + fim);
    }
     public static long carregarMemoria(){
		
		ArrayList<Integer> list = new ArrayList<Integer>();
		for(int i = 0; i<1000000; i++){
		list.add(i);	
		}
		return Runtime.getRuntime().freeMemory();
	}   
    public void enter(){
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel4 = new javax.swing.JPanel();
        lblcodcor = new javax.swing.JLabel();
        lblcodproduto = new javax.swing.JLabel();
        txtp = new javax.swing.JTextField();
        lblcodproduto2 = new javax.swing.JLabel();
        chbp = new javax.swing.JCheckBox();
        txtm = new javax.swing.JTextField();
        lblcodproduto3 = new javax.swing.JLabel();
        chbm = new javax.swing.JCheckBox();
        txtg = new javax.swing.JTextField();
        lblcodproduto4 = new javax.swing.JLabel();
        chbg = new javax.swing.JCheckBox();
        txtgg = new javax.swing.JTextField();
        lblcodproduto5 = new javax.swing.JLabel();
        chbgg = new javax.swing.JCheckBox();
        txteg = new javax.swing.JTextField();
        lblcodproduto6 = new javax.swing.JLabel();
        chbeg = new javax.swing.JCheckBox();
        txtexg = new javax.swing.JTextField();
        lblcodproduto7 = new javax.swing.JLabel();
        chbexg = new javax.swing.JCheckBox();
        lblcodproduto8 = new javax.swing.JLabel();
        lblcodproduto9 = new javax.swing.JLabel();
        cmbproduto = new javax.swing.JComboBox();
        cmbcor = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        txtp1 = new javax.swing.JTextField();
        lblcodproduto10 = new javax.swing.JLabel();
        txtm1 = new javax.swing.JTextField();
        lblcodproduto11 = new javax.swing.JLabel();
        txtg1 = new javax.swing.JTextField();
        lblcodproduto12 = new javax.swing.JLabel();
        txtgg1 = new javax.swing.JTextField();
        lblcodproduto13 = new javax.swing.JLabel();
        txteg1 = new javax.swing.JTextField();
        lblcodproduto14 = new javax.swing.JLabel();
        txtexg1 = new javax.swing.JTextField();
        lblcodproduto15 = new javax.swing.JLabel();
        txtpreco1 = new javax.swing.JTextField();
        lblcodproduto17 = new javax.swing.JLabel();
        btninserir = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrada Produto Acabado");
        jPanel4.setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        lblcodcor.setText("jLabel4");
        jPanel4.add(lblcodcor);
        lblcodcor.setBounds(290, 20, 34, 14);

        lblcodproduto.setText("jLabel4");
        jPanel4.add(lblcodproduto);
        lblcodproduto.setBounds(120, 20, 34, 14);

        txtp.setText("0");
        txtp.setEnabled(false);
        txtp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpFocusGained(evt);
            }
        });
        txtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpKeyTyped(evt);
            }
        });

        jPanel4.add(txtp);
        txtp.setBounds(30, 100, 40, 20);

        lblcodproduto2.setText("P");
        jPanel4.add(lblcodproduto2);
        lblcodproduto2.setBounds(30, 80, 20, 14);

        chbp.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chbp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chbp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbpItemStateChanged(evt);
            }
        });

        jPanel4.add(chbp);
        chbp.setBounds(50, 80, 20, 13);

        txtm.setText("0");
        txtm.setEnabled(false);
        txtm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmFocusGained(evt);
            }
        });
        txtm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmKeyTyped(evt);
            }
        });

        jPanel4.add(txtm);
        txtm.setBounds(90, 100, 40, 20);

        lblcodproduto3.setText("M");
        jPanel4.add(lblcodproduto3);
        lblcodproduto3.setBounds(90, 80, 20, 14);

        chbm.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chbm.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chbm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbmItemStateChanged(evt);
            }
        });

        jPanel4.add(chbm);
        chbm.setBounds(110, 80, 20, 13);

        txtg.setText("0");
        txtg.setEnabled(false);
        txtg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtgFocusGained(evt);
            }
        });
        txtg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgKeyTyped(evt);
            }
        });

        jPanel4.add(txtg);
        txtg.setBounds(150, 100, 40, 20);

        lblcodproduto4.setText("G");
        jPanel4.add(lblcodproduto4);
        lblcodproduto4.setBounds(150, 80, 20, 14);

        chbg.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chbg.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chbg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbgItemStateChanged(evt);
            }
        });

        jPanel4.add(chbg);
        chbg.setBounds(170, 80, 20, 13);

        txtgg.setText("0");
        txtgg.setEnabled(false);
        txtgg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtggFocusGained(evt);
            }
        });
        txtgg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtggKeyTyped(evt);
            }
        });

        jPanel4.add(txtgg);
        txtgg.setBounds(210, 100, 40, 20);

        lblcodproduto5.setText("GG");
        jPanel4.add(lblcodproduto5);
        lblcodproduto5.setBounds(210, 80, 20, 14);

        chbgg.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chbgg.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chbgg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbggItemStateChanged(evt);
            }
        });

        jPanel4.add(chbgg);
        chbgg.setBounds(230, 80, 20, 13);

        txteg.setText("0");
        txteg.setEnabled(false);
        txteg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtegFocusGained(evt);
            }
        });
        txteg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtegKeyTyped(evt);
            }
        });

        jPanel4.add(txteg);
        txteg.setBounds(270, 100, 40, 20);

        lblcodproduto6.setText("EG");
        jPanel4.add(lblcodproduto6);
        lblcodproduto6.setBounds(270, 80, 20, 14);

        chbeg.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chbeg.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chbeg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbegItemStateChanged(evt);
            }
        });

        jPanel4.add(chbeg);
        chbeg.setBounds(290, 80, 20, 13);

        txtexg.setText("0");
        txtexg.setEnabled(false);
        txtexg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtexgFocusGained(evt);
            }
        });
        txtexg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtexgKeyTyped(evt);
            }
        });

        jPanel4.add(txtexg);
        txtexg.setBounds(330, 100, 40, 20);

        lblcodproduto7.setText("EXG");
        jPanel4.add(lblcodproduto7);
        lblcodproduto7.setBounds(330, 80, 30, 14);

        chbexg.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chbexg.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chbexg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbexgItemStateChanged(evt);
            }
        });

        jPanel4.add(chbexg);
        chbexg.setBounds(360, 80, 20, 13);

        lblcodproduto8.setText("Produto");
        jPanel4.add(lblcodproduto8);
        lblcodproduto8.setBounds(10, 20, 60, 14);

        lblcodproduto9.setText("Cor");
        jPanel4.add(lblcodproduto9);
        lblcodproduto9.setBounds(250, 20, 60, 14);

        cmbproduto.setMaximumRowCount(5);
        cmbproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprodutoActionPerformed(evt);
            }
        });

        jPanel4.add(cmbproduto);
        cmbproduto.setBounds(10, 40, 230, 20);

        cmbcor.setMaximumRowCount(5);
        cmbcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcorActionPerformed(evt);
            }
        });
        cmbcor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbcorFocusLost(evt);
            }
        });

        jPanel4.add(cmbcor);
        cmbcor.setBounds(250, 40, 250, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 10, 510, 130);

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldo Atual"));
        txtp1.setEditable(false);
        txtp1.setText("0");
        txtp1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtp1FocusGained(evt);
            }
        });
        txtp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtp1KeyTyped(evt);
            }
        });

        jPanel1.add(txtp1);
        txtp1.setBounds(30, 50, 40, 20);

        lblcodproduto10.setText("P");
        jPanel1.add(lblcodproduto10);
        lblcodproduto10.setBounds(30, 30, 20, 14);

        txtm1.setEditable(false);
        txtm1.setText("0");
        txtm1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtm1FocusGained(evt);
            }
        });
        txtm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtm1KeyTyped(evt);
            }
        });

        jPanel1.add(txtm1);
        txtm1.setBounds(90, 50, 40, 20);

        lblcodproduto11.setText("M");
        jPanel1.add(lblcodproduto11);
        lblcodproduto11.setBounds(90, 30, 20, 14);

        txtg1.setEditable(false);
        txtg1.setText("0");
        txtg1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtg1FocusGained(evt);
            }
        });
        txtg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtg1KeyTyped(evt);
            }
        });

        jPanel1.add(txtg1);
        txtg1.setBounds(150, 50, 40, 20);

        lblcodproduto12.setText("G");
        jPanel1.add(lblcodproduto12);
        lblcodproduto12.setBounds(150, 30, 20, 14);

        txtgg1.setEditable(false);
        txtgg1.setText("0");
        txtgg1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtgg1FocusGained(evt);
            }
        });
        txtgg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgg1KeyTyped(evt);
            }
        });

        jPanel1.add(txtgg1);
        txtgg1.setBounds(210, 50, 40, 20);

        lblcodproduto13.setText("GG");
        jPanel1.add(lblcodproduto13);
        lblcodproduto13.setBounds(210, 30, 20, 14);

        txteg1.setEditable(false);
        txteg1.setText("0");
        txteg1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txteg1FocusGained(evt);
            }
        });
        txteg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txteg1KeyTyped(evt);
            }
        });

        jPanel1.add(txteg1);
        txteg1.setBounds(270, 50, 40, 20);

        lblcodproduto14.setText("EG");
        jPanel1.add(lblcodproduto14);
        lblcodproduto14.setBounds(270, 30, 20, 14);

        txtexg1.setEditable(false);
        txtexg1.setText("0");
        txtexg1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtexg1FocusGained(evt);
            }
        });
        txtexg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtexg1KeyTyped(evt);
            }
        });

        jPanel1.add(txtexg1);
        txtexg1.setBounds(330, 50, 40, 20);

        lblcodproduto15.setText("EXG");
        jPanel1.add(lblcodproduto15);
        lblcodproduto15.setBounds(330, 30, 30, 14);

        txtpreco1.setEditable(false);
        txtpreco1.setText("0.00");
        txtpreco1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpreco1FocusGained(evt);
            }
        });
        txtpreco1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpreco1KeyTyped(evt);
            }
        });

        jPanel1.add(txtpreco1);
        txtpreco1.setBounds(400, 50, 90, 20);

        lblcodproduto17.setText("Pre\u00e7o Atual");
        jPanel1.add(lblcodproduto17);
        lblcodproduto17.setBounds(400, 30, 80, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 150, 510, 80);

        btninserir.setFont(new java.awt.Font("Tahoma", 1, 12));
        btninserir.setText("Salvar");
        btninserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninserirActionPerformed(evt);
            }
        });

        getContentPane().add(btninserir);
        btninserir.setBounds(20, 240, 80, 30);

        btnlimpar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        getContentPane().add(btnlimpar);
        btnlimpar.setBounds(110, 240, 80, 30);

        btnsair.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnsair.setText("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        getContentPane().add(btnsair);
        btnsair.setBounds(200, 240, 80, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-536)/2, (screenSize.height-308)/2, 536, 308);
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtpreco1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpreco1KeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_txtpreco1KeyTyped
    
    private void txtpreco1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpreco1FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_txtpreco1FocusGained
    public static String converterDoubleString(double precoDouble) {
        /*Transformando um double em 2 casas decimais*/
        DecimalFormat fmt = new DecimalFormat("0.00");    //limita o número de casas decimais
        String string = fmt.format(precoDouble);
        String[] part = string.split("[,]");
        String preco = part[0]+"."+part[1];
        return preco;
    }
    private void cmbcorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbcorFocusLost
// TODO add your handling code here:
        try {
            con_saldo= new conexao();
            con_saldo.conecta();
            con_saldo.executeSQL("SELECT qt_p, qt_m,qt_g,qt_gg,qt_eg,qt_exg, vl_unitario FROM produtoacabado where cd_produto='"
                    + Integer.parseInt(lblcodproduto.getText())
                    + "' and cd_cor = '"
                    + Integer.parseInt(lblcodcor.getText())
                    + "'");
            
            con_saldo.resultset.first();
            
            txtp1.setText(con_saldo.resultset.getString("qt_p"));
            txtm1.setText(con_saldo.resultset.getString("qt_m"));
            txtg1.setText(con_saldo.resultset.getString("qt_g"));
            txtgg1.setText(con_saldo.resultset.getString("qt_gg"));
            txteg1.setText(con_saldo.resultset.getString("qt_eg"));
            txtexg1.setText(con_saldo.resultset.getString("qt_exg"));
            txtpreco1.setText(converterDoubleString(con_saldo.resultset.getDouble("vl_unitario")));
            
            qtdestoquetinhap = (con_saldo.resultset.getInt("qt_p"));
            qtdestoquetinham = (con_saldo.resultset.getInt("qt_m"));
            qtdestoquetinhag = (con_saldo.resultset.getInt("qt_g"));
            qtdestoquetinhagg = (con_saldo.resultset.getInt("qt_gg"));
            qtdestoquetinhaeg = (con_saldo.resultset.getInt("qt_eg"));
            qtdestoquetinhaexg = (con_saldo.resultset.getInt("qt_exg"));
            
            
        } catch(SQLException erro) {
            if(txtp1.getText().equals("0") && txtm1.getText().equals("0")&& txtg1.getText().equals("0")&& txtgg1.getText().equals("0")&& txteg1.getText().equals("0")&& txtexg1.getText().equals("0")){
                
                JOptionPane.showMessageDialog(null,"Combinação Produto/ Cor encontrada.\n   Combinação incluída com sucesso!");
                
               
                
                try {
                  
                    String sqlinsertsaldo ="INSERT INTO produtoacabado (cd_numlote, cd_produto, cd_cor, qt_p, qt_m, qt_g, qt_gg, qt_eg, qt_exg) VALUES('"+
                        0 +"','"+
                        Integer.parseInt(lblcodproduto.getText())+"','"+
                        Integer.parseInt(lblcodcor.getText())+"','"+
                        Integer.parseInt(txtp.getText())+"','"+
                        Integer.parseInt(txtm.getText())+"','"+
                        Integer.parseInt(txtg.getText())+"','"+
                        Integer.parseInt(txtgg.getText())+"','"+
                        Integer.parseInt(txteg.getText())+"','"+
                        Integer.parseInt(txtexg.getText())+"')";  
                  //  JOptionPane.showMessageDialog(null, sqlinsertsaldo);
                    con_saldo.statement.executeUpdate(sqlinsertsaldo);
                    
                    con_saldo.executeSQL("select * from produtoacabado");
                    
                    txtp1.setText("0");
                    txtm1.setText("0");
                    txtg1.setText("0");
                    txtgg1.setText("0");
                    txteg1.setText("0");
                    txtexg1.setText("0");
                    qtdestoquetinhap=0;
                    qtdestoquetinham=0;
                    qtdestoquetinhag=0;
                    qtdestoquetinhagg=0;
                    qtdestoquetinhaeg=0;
                    qtdestoquetinhaexg=0;
                    
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
                
                
            }
        }
    }//GEN-LAST:event_cmbcorFocusLost
    
    private void cmbcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcorActionPerformed
// TODO add your handling code here:
        if(iniciacombo == 1){
            try {
                
                con_cor.resultset.first();
                String igual = "n";
                while(igual == "n"){
                    if(con_cor.resultset.getString("nm_cor").equals(cmbcor.getSelectedItem())){
                        igual = "s";
                    } else
                        con_cor.resultset.next();
                }
                lblcodcor.setText(con_cor.resultset.getString(String.valueOf("cd_cor")));
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                
            }
        }
        iniciacombo=1;
    }//GEN-LAST:event_cmbcorActionPerformed
    
    private void cmbprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprodutoActionPerformed
// TODO add your handling code here:
        if(iniciacombo == 1){
            try {
                
                con_produto.resultset.first();
                String igual = "n";
                while(igual == "n"){
                    if(con_produto.resultset.getString("nm_produto").equals(cmbproduto.getSelectedItem())){
                        igual = "s";
                    } else
                        con_produto.resultset.next();
                }
                lblcodproduto.setText(con_produto.resultset.getString(String.valueOf("cd_produto")));
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                
            }
        }
        iniciacombo=1;
    }//GEN-LAST:event_cmbprodutoActionPerformed
    
    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed
 public void zerar(){
        txtp.setText("0");
        txtp.setEnabled(false);
        txtm.setText("0");
        txtm.setEnabled(false);
        txtg.setText("0");
        txtg.setEnabled(false);
        txtgg.setText("0");
        txtgg.setEnabled(false);
        txteg.setText("0");
        txteg.setEnabled(false);
        txtexg.setText("0");
        txtexg.setEnabled(false);
        chbp.setSelected(false);
        chbm.setSelected(false);
        chbg.setSelected(false);
        chbgg.setSelected(false);
        chbeg.setSelected(false);
        chbexg.setSelected(false);
        txtp1.setText("0");
        txtm1.setText("0");
        txtg1.setText("0");
        txtgg1.setText("0");
        txteg1.setText("0");
        txtexg1.setText("0");
        cmbcor.setSelectedIndex(0);
        cmbproduto.setSelectedIndex(0);
        txtpreco1.setText("0.00");    
 } 
    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
// TODO add your handling code here:
        txtp.setText("0");
        txtp.setEnabled(false);
        txtm.setText("0");
        txtm.setEnabled(false);
        txtg.setText("0");
        txtg.setEnabled(false);
        txtgg.setText("0");
        txtgg.setEnabled(false);
        txteg.setText("0");
        txteg.setEnabled(false);
        txtexg.setText("0");
        txtexg.setEnabled(false);
        chbp.setSelected(false);
        chbm.setSelected(false);
        chbg.setSelected(false);
        chbgg.setSelected(false);
        chbeg.setSelected(false);
        chbexg.setSelected(false);
        txtp1.setText("0");
        txtm1.setText("0");
        txtg1.setText("0");
        txtgg1.setText("0");
        txteg1.setText("0");
        txtexg1.setText("0");
        cmbcor.setSelectedIndex(0);
        cmbproduto.setSelectedIndex(0);
        txtpreco1.setText("0.00");
        
    }//GEN-LAST:event_btnlimparActionPerformed
    
    private void btninserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninserirActionPerformed
// TODO add your handling code here:
            
        try {
            int estoqueatualp = 0;
            int estoqueatualm = 0;
            int estoqueatualg = 0;
            int estoqueatualgg = 0;
            int estoqueatualeg = 0;
            int estoqueatualexg = 0; 
            
            estoqueatualp = qtdestoquetinhap +  Integer.parseInt(txtp.getText());
            estoqueatualm = qtdestoquetinham +  Integer.parseInt(txtm.getText());
            estoqueatualg = qtdestoquetinhag +  Integer.parseInt(txtg.getText());
            estoqueatualgg = qtdestoquetinhagg +  Integer.parseInt(txtgg.getText());
            estoqueatualeg = qtdestoquetinhaeg +  Integer.parseInt(txteg.getText());
            estoqueatualexg = qtdestoquetinhaexg +  Integer.parseInt(txtexg.getText());
            
            qtdestoquetinhap=0;
            qtdestoquetinham=0;
            qtdestoquetinhag=0;
            qtdestoquetinhagg=0;
            qtdestoquetinhaeg=0;
            qtdestoquetinhaexg=0;
            
            String sqlinsertsaldo = "Update produtoacabado set qt_p= '"+estoqueatualp+"',"+
                    "qt_m= '"+estoqueatualm+"',"+
                    "qt_g= '"+estoqueatualg+"',"+
                    "qt_gg= '"+estoqueatualgg+"',"+
                    "qt_eg= '"+estoqueatualeg+"',"+
                    "qt_exg= '"+estoqueatualexg+"' where cd_produto ='"+Integer.parseInt(lblcodproduto.getText())+"' " +
                    "and cd_cor = '"+Integer.parseInt(lblcodcor.getText())+"' ";
           
            
            con_saldo.statement.executeUpdate(sqlinsertsaldo);
            
            //con_saldo.executeSQL("select * from produtoacabado");
            con_saldo.executeSQL("SELECT qt_p, qt_m,qt_g,qt_gg,qt_eg,qt_exg, vl_unitario FROM produtoacabado where cd_produto='"
                    + Integer.parseInt(lblcodproduto.getText())
                    + "' and cd_cor = '"
                    + Integer.parseInt(lblcodcor.getText())
                    + "'");
            //JOptionPane.showMessageDialog(null, sqlinsertsaldo);
            
            con_saldo.resultset.first();
           
            JOptionPane.showMessageDialog(null, "Saldo atual -  "+ con_saldo.resultset.getInt("qt_p")+ " Peças P \n                          " +  con_saldo.resultset.getInt("qt_m")+ " Peças M \n                          "+ con_saldo.resultset.getInt("qt_g")+ " Peças G \n                          "+ con_saldo.resultset.getInt("qt_gg")+ " Peças GG \n                          " + con_saldo.resultset.getInt("qt_eg")+ " Peças EG \n                          "+ con_saldo.resultset.getInt("qt_exg")+ " Peças EXG \n                          " ) ;
            
            txtp1.setText(con_saldo.resultset.getString("qt_p"));
            txtm1.setText(con_saldo.resultset.getString("qt_m"));
            txtg1.setText(con_saldo.resultset.getString("qt_g"));
            txtgg1.setText(con_saldo.resultset.getString("qt_gg"));
            txteg1.setText(con_saldo.resultset.getString("qt_eg"));
            txtexg1.setText(con_saldo.resultset.getString("qt_exg"));
            txtpreco1.setText(converterDoubleString(con_saldo.resultset.getDouble("vl_unitario")));
            
            JOptionPane.showMessageDialog(null,"Gravação realizado com sucesso!");
            
            
            
            txtp1.setText("0");
            txtm1.setText("0");
            txtg1.setText("0");
            txtgg1.setText("0");
            txteg1.setText("0");
            txtexg1.setText("0");
            cmbcor.setSelectedIndex(0);
            cmbproduto.setSelectedIndex(0);
            txtp.setText("0");
            txtp.setEnabled(false);
            txtm.setText("0");
            txtm.setEnabled(false);
            txtg.setText("0");
            txtg.setEnabled(false);
            txtgg.setText("0");
            txtgg.setEnabled(false);
            txteg.setText("0");
            txteg.setEnabled(false);
            txtexg.setText("0");
            txtexg.setEnabled(false);
            chbp.setSelected(false);
            chbm.setSelected(false);
            chbg.setSelected(false);
            chbgg.setSelected(false);
            chbeg.setSelected(false);
            chbexg.setSelected(false);
            txtpreco1.setText("0.00");
            
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btninserirActionPerformed
    
    private void txtexg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtexg1KeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_txtexg1KeyTyped
    
    private void txtexg1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtexg1FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_txtexg1FocusGained
    
    private void txteg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteg1KeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_txteg1KeyTyped
    
    private void txteg1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txteg1FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_txteg1FocusGained
    
    private void txtgg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgg1KeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_txtgg1KeyTyped
    
    private void txtgg1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgg1FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_txtgg1FocusGained
    
    private void txtg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtg1KeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_txtg1KeyTyped
    
    private void txtg1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtg1FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_txtg1FocusGained
    
    private void txtm1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtm1KeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_txtm1KeyTyped
    
    private void txtm1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtm1FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_txtm1FocusGained
    
    private void txtp1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtp1KeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_txtp1KeyTyped
    
    private void txtp1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtp1FocusGained
// TODO add your handling code here:
    }//GEN-LAST:event_txtp1FocusGained
    
    private void chbexgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbexgItemStateChanged
// TODO add your handling code here:
        if (chbexg.isSelected()){
            
            txtexg.setEnabled(true);
            txtexg.requestFocus();
        }
        if (!chbexg.isSelected()){
            txtexg.setEnabled(false);
            
        }
    }//GEN-LAST:event_chbexgItemStateChanged
    
    private void txtexgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtexgKeyTyped
// TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtexgKeyTyped
    
    private void txtexgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtexgFocusGained
// TODO add your handling code here:
        txtexg.selectAll();
    }//GEN-LAST:event_txtexgFocusGained
    
    private void chbegItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbegItemStateChanged
// TODO add your handling code here:
        if (chbeg.isSelected()){
            
            txteg.setEnabled(true);
            txteg.requestFocus();
        }
        if (!chbeg.isSelected()){
            txteg.setEnabled(false);
            
        }
    }//GEN-LAST:event_chbegItemStateChanged
    
    private void txtegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtegKeyTyped
// TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtegKeyTyped
    
    private void txtegFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtegFocusGained
// TODO add your handling code here:
        txteg.selectAll();
    }//GEN-LAST:event_txtegFocusGained
    
    private void chbggItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbggItemStateChanged
// TODO add your handling code here:
        if (chbgg.isSelected()){
            
            txtgg.setEnabled(true);
            txtgg.requestFocus();
        }
        if (!chbgg.isSelected()){
            txtgg.setEnabled(false);
            
        }
    }//GEN-LAST:event_chbggItemStateChanged
    
    private void txtggKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtggKeyTyped
// TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtggKeyTyped
    
    private void txtggFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtggFocusGained
// TODO add your handling code here:
        txtgg.selectAll();
    }//GEN-LAST:event_txtggFocusGained
    
    private void chbgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbgItemStateChanged
// TODO add your handling code here:
        if (chbg.isSelected()){
            
            txtg.setEnabled(true);
            txtg.requestFocus();
        }
        if (!chbg.isSelected()){
            txtg.setEnabled(false);
            
        }
    }//GEN-LAST:event_chbgItemStateChanged
    
    private void txtgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgKeyTyped
// TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtgKeyTyped
    
    private void txtgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgFocusGained
// TODO add your handling code here:
        txtg.selectAll();
    }//GEN-LAST:event_txtgFocusGained
    
    private void chbmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbmItemStateChanged
// TODO add your handling code here:
        if (chbm.isSelected()){
            
            txtm.setEnabled(true);
            txtm.requestFocus();
            
        }
        if (!chbm.isSelected()){
            txtm.setEnabled(false);
            
        }
    }//GEN-LAST:event_chbmItemStateChanged
    
    private void txtmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmKeyTyped
// TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtmKeyTyped
    
    private void txtmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmFocusGained
// TODO add your handling code here:
        txtm.selectAll();
    }//GEN-LAST:event_txtmFocusGained
    
    private void chbpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbpItemStateChanged
// TODO add your handling code here:
        if (chbp.isSelected()){
            txtp.setEnabled(true);
            txtp.requestFocus();
            
            
        }
        if (!chbp.isSelected()){
            txtp.setEnabled(false);
            
        }
    }//GEN-LAST:event_chbpItemStateChanged
    
    private void txtpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpKeyTyped
// TODO add your handling code here:
        // Só aceita numero
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtpKeyTyped
    
    private void txtpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpFocusGained
// TODO add your handling code here:
        txtp.selectAll();
    }//GEN-LAST:event_txtpFocusGained
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaProdutoAcabadoDireto().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninserir;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnsair;
    private javax.swing.JCheckBox chbeg;
    private javax.swing.JCheckBox chbexg;
    private javax.swing.JCheckBox chbg;
    private javax.swing.JCheckBox chbgg;
    private javax.swing.JCheckBox chbm;
    private javax.swing.JCheckBox chbp;
    private javax.swing.JComboBox cmbcor;
    private javax.swing.JComboBox cmbproduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblcodcor;
    private javax.swing.JLabel lblcodproduto;
    private javax.swing.JLabel lblcodproduto10;
    private javax.swing.JLabel lblcodproduto11;
    private javax.swing.JLabel lblcodproduto12;
    private javax.swing.JLabel lblcodproduto13;
    private javax.swing.JLabel lblcodproduto14;
    private javax.swing.JLabel lblcodproduto15;
    private javax.swing.JLabel lblcodproduto17;
    private javax.swing.JLabel lblcodproduto2;
    private javax.swing.JLabel lblcodproduto3;
    private javax.swing.JLabel lblcodproduto4;
    private javax.swing.JLabel lblcodproduto5;
    private javax.swing.JLabel lblcodproduto6;
    private javax.swing.JLabel lblcodproduto7;
    private javax.swing.JLabel lblcodproduto8;
    private javax.swing.JLabel lblcodproduto9;
    private javax.swing.JTextField txteg;
    private javax.swing.JTextField txteg1;
    private javax.swing.JTextField txtexg;
    private javax.swing.JTextField txtexg1;
    private javax.swing.JTextField txtg;
    private javax.swing.JTextField txtg1;
    private javax.swing.JTextField txtgg;
    private javax.swing.JTextField txtgg1;
    private javax.swing.JTextField txtm;
    private javax.swing.JTextField txtm1;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtp1;
    private javax.swing.JTextField txtpreco1;
    // End of variables declaration//GEN-END:variables
    
}
