/*
 * Principal.java
 *
 * Created on 1 de Setembro de 2011, 19:56
 */
package View;

import Controle.conexao;
import Relatorio.Rel_Saldo_Tecido;
import Relatorio.Rel_Saldo_Tecido;
import Utilitarios.data;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import Modelo.*;
import java.util.ArrayList;
import java.util.HashSet;
import Relatorio.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author  Familia-Silva
 */
public class Principal extends javax.swing.JFrame {

    private conexao con_cliente, con_produto, con_cor, con_email, con_vendedor, con_data, con_orcamento;
    data mostra_data;
    private String seta_look;

    /** Creates new form Principal */
    public Principal() {
        initComponents();


        Runtime rt = Runtime.getRuntime();
        int MB = 1048576; // total de bytes em 1MB

        double total = rt.maxMemory() / MB;
        double inicio = total - (carregarMemoria() / MB);

        //System.out.println(total);
        //System.out.println(inicio);

        // Metodo de limpaza
        rt.runFinalization();
        rt.gc();

        double fim = total - rt.freeMemory() / MB;
        System.out.println("Início = " + inicio + "Fim = " + fim);




        con_data = new conexao();
        con_data.conecta();

        mostra_data = new data();
        mostra_data.le_data();
        mostra_data.le_hora();
        this.setTitle("Principal       " + mostra_data.dia_semana + ", " + mostra_data.dia + " de " + mostra_data.mes + " de " + mostra_data.ano + "     " + mostra_data.hora);
        timer1.start();
        enter();
        setResizable(false);
    }

    public void enter() {
// Enter simula tecla Tab
        HashSet conj = new HashSet(getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        menuBar2 = new java.awt.MenuBar();
        menu2 = new java.awt.Menu();
        popupMenu2 = new java.awt.PopupMenu();
        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        lblusuario = new javax.swing.JLabel();
        lblimagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastros = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenuItem();
        Fornec = new javax.swing.JMenuItem();
        Vendedor = new javax.swing.JMenuItem();
        Terceirizada = new javax.swing.JMenuItem();
        Cliente2 = new javax.swing.JMenuItem();
        NotaFiscal = new javax.swing.JMenuItem();
        MateriaPri = new javax.swing.JMenuItem();
        SaidaMateriaPrima = new javax.swing.JMenuItem();
        FechamentoProduto = new javax.swing.JMenuItem();
        EntradaDireta = new javax.swing.JMenuItem();
        Cadastros1 = new javax.swing.JMenu();
        T = new javax.swing.JMenuItem();
        Fornec1 = new javax.swing.JMenuItem();
        Produto = new javax.swing.JMenuItem();
        Vendedor1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        Vendedor2 = new javax.swing.JMenuItem();
        Consulta = new javax.swing.JMenu();
        CCliente = new javax.swing.JMenuItem();
        CTercerizada = new javax.swing.JMenuItem();
        CVendedor = new javax.swing.JMenuItem();
        CFornecedor = new javax.swing.JMenuItem();
        CAniversario = new javax.swing.JMenuItem();
        Cadastros2 = new javax.swing.JMenu();
        Tec = new javax.swing.JMenuItem();
        Aviam = new javax.swing.JMenuItem();
        Produto1 = new javax.swing.JMenuItem();
        Cor = new javax.swing.JMenuItem();
        Preco = new javax.swing.JMenuItem();
        CProdutoAcabado = new javax.swing.JMenuItem();
        CBalanco = new javax.swing.JMenuItem();
        CFechamentoProduto = new javax.swing.JMenuItem();
        CMateriaPrima = new javax.swing.JMenuItem();
        CMateriaPrima1 = new javax.swing.JMenuItem();
        CMostruario = new javax.swing.JMenuItem();
        COrcamento = new javax.swing.JMenuItem();
        CPedido = new javax.swing.JMenuItem();
        CGeral = new javax.swing.JMenuItem();
        Pedido = new javax.swing.JMenu();
        OrcamentoPedido = new javax.swing.JMenuItem();
        VendaBalcao = new javax.swing.JMenuItem();
        VendaCarteira = new javax.swing.JMenuItem();
        Contas = new javax.swing.JMenu();
        Apagar = new javax.swing.JMenuItem();
        AReceber = new javax.swing.JMenuItem();
        AReceberBalcao = new javax.swing.JMenuItem();
        AReceberCarteira = new javax.swing.JMenuItem();
        Usuario = new javax.swing.JMenu();
        Novo = new javax.swing.JMenuItem();
        Excluir = new javax.swing.JMenuItem();
        Relatorio = new javax.swing.JMenu();
        ProdutoAcabado = new javax.swing.JMenuItem();
        Tecido = new javax.swing.JMenuItem();
        Aviamento = new javax.swing.JMenuItem();
        Utilitarios = new javax.swing.JMenu();
        Padrao = new javax.swing.JMenuItem();
        Windows = new javax.swing.JMenuItem();
        Mofit = new javax.swing.JMenuItem();
        Liquid = new javax.swing.JMenuItem();

        menu1.setLabel("Menu");
        menuBar1.add(menu1);

        popupMenu1.setLabel("PopupMenu");

        menu2.setLabel("Menu");
        menuBar2.add(menu2);

        popupMenu2.setLabel("PopupMenu");

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblusuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lblusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblusuario.setRequestFocusEnabled(false);
        lblusuario.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(lblusuario);
        lblusuario.setBounds(340, 310, 130, 14);

        lblimagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/principal1.jpg"))); // NOI18N
        lblimagem.setText("jLabel1");
        getContentPane().add(lblimagem);
        lblimagem.setBounds(0, 0, 490, 350);

        Cadastros.setMnemonic('c');
        Cadastros.setText("Cadastros");
        Cadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrosActionPerformed(evt);
            }
        });

        Cliente.setMnemonic('c');
        Cliente.setText("Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        Cadastros.add(Cliente);

        Fornec.setMnemonic('f');
        Fornec.setText("Fornecedor");
        Fornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FornecActionPerformed(evt);
            }
        });
        Cadastros.add(Fornec);

        Vendedor.setMnemonic('v');
        Vendedor.setText("Vendedor");
        Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendedorActionPerformed(evt);
            }
        });
        Cadastros.add(Vendedor);

        Terceirizada.setMnemonic('t');
        Terceirizada.setText("Terceirizada");
        Terceirizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerceirizadaActionPerformed(evt);
            }
        });
        Cadastros.add(Terceirizada);

        Cliente2.setMnemonic('m');
        Cliente2.setText("Mostruário");
        Cliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente2ActionPerformed(evt);
            }
        });
        Cadastros.add(Cliente2);

        NotaFiscal.setMnemonic('n');
        NotaFiscal.setText("Nota Fiscal");
        NotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaFiscalActionPerformed(evt);
            }
        });
        Cadastros.add(NotaFiscal);

        MateriaPri.setMnemonic('p');
        MateriaPri.setText("Matéria Prima (entrada)");
        MateriaPri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriaPriActionPerformed(evt);
            }
        });
        Cadastros.add(MateriaPri);

        SaidaMateriaPrima.setMnemonic('m');
        SaidaMateriaPrima.setText("Matéria Prima (saída)");
        SaidaMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaMateriaPrimaActionPerformed(evt);
            }
        });
        Cadastros.add(SaidaMateriaPrima);

        FechamentoProduto.setMnemonic('f');
        FechamentoProduto.setText("Fechamento Produto (envio)");
        FechamentoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechamentoProdutoActionPerformed(evt);
            }
        });
        Cadastros.add(FechamentoProduto);

        EntradaDireta.setMnemonic('a');
        EntradaDireta.setText("Produto Acabado (entrada)");
        EntradaDireta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaDiretaActionPerformed(evt);
            }
        });
        Cadastros.add(EntradaDireta);

        Cadastros1.setMnemonic('o');
        Cadastros1.setText("Outros");
        Cadastros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastros1ActionPerformed(evt);
            }
        });

        T.setMnemonic('t');
        T.setText("Tecido");
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });
        Cadastros1.add(T);

        Fornec1.setMnemonic('a');
        Fornec1.setText("Aviamento");
        Fornec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fornec1ActionPerformed(evt);
            }
        });
        Cadastros1.add(Fornec1);

        Produto.setMnemonic('p');
        Produto.setText("Produto");
        Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoActionPerformed(evt);
            }
        });
        Cadastros1.add(Produto);

        Vendedor1.setMnemonic('c');
        Vendedor1.setText("Cor");
        Vendedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendedor1ActionPerformed(evt);
            }
        });
        Cadastros1.add(Vendedor1);

        Cadastros.add(Cadastros1);
        Cadastros.add(jSeparator1);

        Vendedor2.setMnemonic('S');
        Vendedor2.setText("Sair");
        Vendedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendedor2ActionPerformed(evt);
            }
        });
        Cadastros.add(Vendedor2);

        jMenuBar1.add(Cadastros);

        Consulta.setMnemonic('o');
        Consulta.setText("Consulta");
        Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaActionPerformed(evt);
            }
        });

        CCliente.setMnemonic('c');
        CCliente.setText("Cliente");
        CCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CClienteActionPerformed(evt);
            }
        });
        Consulta.add(CCliente);

        CTercerizada.setMnemonic('t');
        CTercerizada.setText("Terceirizada");
        CTercerizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTercerizadaActionPerformed(evt);
            }
        });
        Consulta.add(CTercerizada);

        CVendedor.setMnemonic('v');
        CVendedor.setText("Vendedor");
        CVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVendedorActionPerformed(evt);
            }
        });
        Consulta.add(CVendedor);

        CFornecedor.setMnemonic('f');
        CFornecedor.setText("Fornecedor");
        CFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFornecedorActionPerformed(evt);
            }
        });
        Consulta.add(CFornecedor);

        CAniversario.setMnemonic('a');
        CAniversario.setText("Aniversario");
        CAniversario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAniversarioActionPerformed(evt);
            }
        });
        Consulta.add(CAniversario);

        Cadastros2.setMnemonic('o');
        Cadastros2.setText("Outros");
        Cadastros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastros2ActionPerformed(evt);
            }
        });

        Tec.setMnemonic('t');
        Tec.setText("Tecido");
        Tec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TecActionPerformed(evt);
            }
        });
        Cadastros2.add(Tec);

        Aviam.setMnemonic('a');
        Aviam.setText("Aviamento");
        Aviam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AviamActionPerformed(evt);
            }
        });
        Cadastros2.add(Aviam);

        Produto1.setMnemonic('p');
        Produto1.setText("Produto");
        Produto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto1ActionPerformed(evt);
            }
        });
        Cadastros2.add(Produto1);

        Cor.setMnemonic('c');
        Cor.setText("Cor");
        Cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorActionPerformed(evt);
            }
        });
        Cadastros2.add(Cor);

        Preco.setMnemonic('r');
        Preco.setText("Preço");
        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });
        Cadastros2.add(Preco);

        Consulta.add(Cadastros2);

        CProdutoAcabado.setMnemonic('p');
        CProdutoAcabado.setText("Produto Acabado (saldo)");
        CProdutoAcabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CProdutoAcabadoActionPerformed(evt);
            }
        });
        Consulta.add(CProdutoAcabado);

        CBalanco.setMnemonic('b');
        CBalanco.setText("Balanço");
        CBalanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBalancoActionPerformed(evt);
            }
        });
        Consulta.add(CBalanco);

        CFechamentoProduto.setMnemonic('e');
        CFechamentoProduto.setText("Fechamento Produto (edita)");
        CFechamentoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFechamentoProdutoActionPerformed(evt);
            }
        });
        Consulta.add(CFechamentoProduto);

        CMateriaPrima.setMnemonic('s');
        CMateriaPrima.setText("Matéria Prima (saldo)");
        CMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMateriaPrimaActionPerformed(evt);
            }
        });
        Consulta.add(CMateriaPrima);

        CMateriaPrima1.setMnemonic('e');
        CMateriaPrima1.setText("Matéria Prima (entrada)");
        CMateriaPrima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMateriaPrima1ActionPerformed(evt);
            }
        });
        Consulta.add(CMateriaPrima1);

        CMostruario.setMnemonic('m');
        CMostruario.setText("Mostruário");
        CMostruario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMostruarioActionPerformed(evt);
            }
        });
        Consulta.add(CMostruario);

        COrcamento.setMnemonic('o');
        COrcamento.setText("Orçamento");
        COrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COrcamentoActionPerformed(evt);
            }
        });
        Consulta.add(COrcamento);

        CPedido.setMnemonic('e');
        CPedido.setText("Pedido");
        CPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPedidoActionPerformed(evt);
            }
        });
        Consulta.add(CPedido);

        CGeral.setMnemonic('g');
        CGeral.setText("Geral");
        CGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGeralActionPerformed(evt);
            }
        });
        Consulta.add(CGeral);

        jMenuBar1.add(Consulta);

        Pedido.setMnemonic('p');
        Pedido.setText("Pedido");
        Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoActionPerformed(evt);
            }
        });

        OrcamentoPedido.setMnemonic('o');
        OrcamentoPedido.setText("Orçamento/ Pedido");
        OrcamentoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrcamentoPedidoActionPerformed(evt);
            }
        });
        Pedido.add(OrcamentoPedido);

        VendaBalcao.setMnemonic('v');
        VendaBalcao.setText("Venda Balcão");
        VendaBalcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendaBalcaoActionPerformed(evt);
            }
        });
        Pedido.add(VendaBalcao);

        VendaCarteira.setMnemonic('c');
        VendaCarteira.setText("Venda Carteira");
        VendaCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendaCarteiraActionPerformed(evt);
            }
        });
        Pedido.add(VendaCarteira);

        jMenuBar1.add(Pedido);

        Contas.setMnemonic('n');
        Contas.setText("Contas");
        Contas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContasActionPerformed(evt);
            }
        });

        Apagar.setMnemonic('p');
        Apagar.setText("À Pagar");
        Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarActionPerformed(evt);
            }
        });
        Contas.add(Apagar);

        AReceber.setMnemonic('a');
        AReceber.setText(" À Receber (Carteira)");
        AReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AReceberActionPerformed(evt);
            }
        });
        Contas.add(AReceber);

        AReceberBalcao.setMnemonic('b');
        AReceberBalcao.setText("Venda Balcão");
        AReceberBalcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AReceberBalcaoActionPerformed(evt);
            }
        });
        Contas.add(AReceberBalcao);

        AReceberCarteira.setMnemonic('c');
        AReceberCarteira.setText("Venda Carteira");
        AReceberCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AReceberCarteiraActionPerformed(evt);
            }
        });
        Contas.add(AReceberCarteira);

        jMenuBar1.add(Contas);

        Usuario.setMnemonic('u');
        Usuario.setText("Usuário");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        Novo.setMnemonic('n');
        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        Usuario.add(Novo);

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        Usuario.add(Excluir);

        jMenuBar1.add(Usuario);

        Relatorio.setMnemonic('r');
        Relatorio.setText("Relatórios");
        Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioActionPerformed(evt);
            }
        });

        ProdutoAcabado.setMnemonic('P');
        ProdutoAcabado.setText("Produto");
        ProdutoAcabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoAcabadoActionPerformed(evt);
            }
        });
        Relatorio.add(ProdutoAcabado);

        Tecido.setMnemonic('t');
        Tecido.setText("Tecido");
        Tecido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TecidoActionPerformed(evt);
            }
        });
        Relatorio.add(Tecido);

        Aviamento.setMnemonic('a');
        Aviamento.setText("Aviamento");
        Aviamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AviamentoActionPerformed(evt);
            }
        });
        Relatorio.add(Aviamento);

        jMenuBar1.add(Relatorio);

        Utilitarios.setMnemonic('t');
        Utilitarios.setText("Utilitários");
        Utilitarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtilitariosActionPerformed(evt);
            }
        });

        Padrao.setMnemonic('p');
        Padrao.setText("Look and Feel - Padrão");
        Padrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PadraoActionPerformed(evt);
            }
        });
        Utilitarios.add(Padrao);

        Windows.setMnemonic('w');
        Windows.setText("Look and Feel - Windows");
        Windows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WindowsActionPerformed(evt);
            }
        });
        Utilitarios.add(Windows);

        Mofit.setMnemonic('m');
        Mofit.setText("Look and Feel - Mofit");
        Mofit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MofitActionPerformed(evt);
            }
        });
        Utilitarios.add(Mofit);

        Liquid.setMnemonic('m');
        Liquid.setText("Look and Feel - Liquid");
        Liquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiquidActionPerformed(evt);
            }
        });
        Utilitarios.add(Liquid);

        jMenuBar1.add(Utilitarios);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-491)/2, (screenSize.height-403)/2, 491, 403);
    }// </editor-fold>//GEN-END:initComponents

    private void AReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AReceberActionPerformed
// TODO add your handling code here:
        new ConsultaReceberCliente().show();
    }//GEN-LAST:event_AReceberActionPerformed

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        try {
// TODO add your handling code here:
            new ConsultaPreco().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_PrecoActionPerformed

    private void AReceberCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AReceberCarteiraActionPerformed
// TODO add your handling code here:
        new ContaReceberCarteira_1_1().show();
    }//GEN-LAST:event_AReceberCarteiraActionPerformed

    private void VendaCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendaCarteiraActionPerformed
// TODO add your handling code here:
        new VendaCarteira_1().show();
    }//GEN-LAST:event_VendaCarteiraActionPerformed

    private void CBalancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBalancoActionPerformed
// TODO add your handling code here:
        new ConsultaBalanco().show();
    }//GEN-LAST:event_CBalancoActionPerformed

    private void Cadastros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastros2ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_Cadastros2ActionPerformed

    private void CorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorActionPerformed
        try {
// TODO add your handling code here:
            new ConsultaCor().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_CorActionPerformed

    private void Produto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto1ActionPerformed
        try {
// TODO add your handling code here:
            new ConsultaProduto().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_Produto1ActionPerformed

    private void AviamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AviamActionPerformed
// TODO add your handling code here:

        try {
// TODO add your handling code here:
            new ConsultaAviamento().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_AviamActionPerformed

    private void TecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TecActionPerformed
// TODO add your handling code here:
        try {
// TODO add your handling code here:
            new ConsultaTecido().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_TecActionPerformed

    private void AviamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AviamentoActionPerformed
// TODO add your handling code here:
        new Rel_Saldo_Aviamento();

    }//GEN-LAST:event_AviamentoActionPerformed

    private void RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_RelatorioActionPerformed

    private void TecidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TecidoActionPerformed
// TODO add your handling code here:
        new Rel_Saldo_Tecido();
    }//GEN-LAST:event_TecidoActionPerformed

    private void ProdutoAcabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoAcabadoActionPerformed
// TODO add your handling code here:
        new Rel_Saldo_ProdutoAcabado();
    }//GEN-LAST:event_ProdutoAcabadoActionPerformed

    private void MateriaPriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriaPriActionPerformed
// TODO add your handling code here:
        new EntradamateriaPrima().show();
    }//GEN-LAST:event_MateriaPriActionPerformed

    private void LiquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiquidActionPerformed
// TODO add your handling code here:
        seta_look = "com.birosoft.liquid.LiquidLookAndFeel";
        lookandfeel();

    }//GEN-LAST:event_LiquidActionPerformed

    private void MofitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MofitActionPerformed
// TODO add your handling code here:
        seta_look = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_MofitActionPerformed
    public void lookandfeel() {

        try {
            UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }

    private void UtilitariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtilitariosActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_UtilitariosActionPerformed

    private void PadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PadraoActionPerformed
// TODO add your handling code here:
        seta_look = "javax.swing.plaf.metal.MetalLookAndFeel";
        lookandfeel();

    }//GEN-LAST:event_PadraoActionPerformed

    private void WindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WindowsActionPerformed
// TODO add your handling code here:
        seta_look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_WindowsActionPerformed

    private void EntradaDiretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaDiretaActionPerformed
// TODO add your handling code here:
        new EntradaProdutoAcabadoDireto().show();
    }//GEN-LAST:event_EntradaDiretaActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        try {
// TODO add your handling code here:
            new ExcluirUsuario().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
// TODO add your handling code here:
        new CadastroUsuario1().show();


    }//GEN-LAST:event_NovoActionPerformed

    private void ContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContasActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_ContasActionPerformed

    private void AReceberBalcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AReceberBalcaoActionPerformed
// TODO add your handling code here:
        new ContaReceber().show();
    }//GEN-LAST:event_AReceberBalcaoActionPerformed

    private void ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarActionPerformed
// TODO add your handling code here:
        new ContaPagar().show();
    }//GEN-LAST:event_ApagarActionPerformed

    private void CGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGeralActionPerformed
// TODO add your handling code here:
        new ConsultaGeral().show();
    }//GEN-LAST:event_CGeralActionPerformed

    private void SaidaMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaMateriaPrimaActionPerformed
// TODO add your handling code here:
        new SaidaMateriaPrima().show();
    }//GEN-LAST:event_SaidaMateriaPrimaActionPerformed

    private void VendaBalcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendaBalcaoActionPerformed
// TODO add your handling code here:
        new VendaBalca().show();
    }//GEN-LAST:event_VendaBalcaoActionPerformed

    private void CFechamentoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFechamentoProdutoActionPerformed
        try {
// TODO add your handling code here:
            new CadastroMostruario_1_1().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_CFechamentoProdutoActionPerformed

    private void FechamentoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechamentoProdutoActionPerformed
        try {
// TODO add your handling code here:
            new CadastroMostruario_1().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_FechamentoProdutoActionPerformed

    private void CPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPedidoActionPerformed
// TODO add your handling code here:
        new ConsultaPedido().show();
    }//GEN-LAST:event_CPedidoActionPerformed

    private void COrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COrcamentoActionPerformed
// TODO add your handling code here:
        new ConsultaOrcamento().show();
    }//GEN-LAST:event_COrcamentoActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
// TODO add your handling code here:

        mostra_data.le_hora();
        this.setTitle("Principal       " + mostra_data.dia_semana + ", " + mostra_data.dia + " de " + mostra_data.mes + " de " + mostra_data.ano + "     " + mostra_data.hora);
    }//GEN-LAST:event_timer1OnTime

    private void PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_PedidoActionPerformed

    private void OrcamentoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrcamentoPedidoActionPerformed
// TODO add your handling code here:
        new CadastroPedido().show();
    }//GEN-LAST:event_OrcamentoPedidoActionPerformed

    private void CMostruarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMostruarioActionPerformed
// TODO add your handling code here:
        new ConsultaMostruario().show();

    }//GEN-LAST:event_CMostruarioActionPerformed

    private void CMateriaPrima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMateriaPrima1ActionPerformed
// TODO add your handling code here:
        new ConsultaEntradaMateriaPrima().show();
    }//GEN-LAST:event_CMateriaPrima1ActionPerformed

    private void CMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMateriaPrimaActionPerformed
// TODO add your handling code here:
        new ConsultaMateriaPrima().show();
    }//GEN-LAST:event_CMateriaPrimaActionPerformed

    private void CProdutoAcabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CProdutoAcabadoActionPerformed
// TODO add your handling code here:
        new ConsultaProdutoAcabado().show();
    }//GEN-LAST:event_CProdutoAcabadoActionPerformed

    private void CAniversarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAniversarioActionPerformed
// TODO add your handling code here:

        new ConsultaAniversario().show();
    }//GEN-LAST:event_CAniversarioActionPerformed

    private void CFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFornecedorActionPerformed
// TODO add your handling code here:
        new ConsultaFornecedor().show();

    }//GEN-LAST:event_CFornecedorActionPerformed

    private void CVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVendedorActionPerformed
// TODO add your handling code here:
        new ConsultaVendedor().show();
    }//GEN-LAST:event_CVendedorActionPerformed

    private void CTercerizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTercerizadaActionPerformed
// TODO add your handling code here:
        new ConsutaTerceiriazada().show();


    }//GEN-LAST:event_CTercerizadaActionPerformed

    private void CClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CClienteActionPerformed
// TODO add your handling code here:

// TODO add your handling code here:
        new ConsultaCliente().show();

    }//GEN-LAST:event_CClienteActionPerformed

    private void Cliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente2ActionPerformed
        try {
// TODO add your handling code here:
            new CadastroMostruario().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_Cliente2ActionPerformed

    private void NotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaFiscalActionPerformed
// TODO add your handling code here:


        new CadastroMateriaPrima().show();

    }//GEN-LAST:event_NotaFiscalActionPerformed

    private void Vendedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendedor2ActionPerformed
// TODO add your handling code here:
        String nome = "Deseja realizar o Back Up do Banco de Dados agora?";
        int opcao_escolha = JOptionPane.showConfirmDialog(null, nome, "Atenção", JOptionPane.YES_NO_OPTION);
        if (opcao_escolha == JOptionPane.YES_OPTION) {

            try {
// TODO add your handling code here:
                //linha de código Backup window 7
                 //         Runtime.getRuntime().exec("C:\\Program Files (x86)\\PostgreSQL\\9.0\\bin\\pg_dump.exe -i -h localhost -p 5432 -U postgres -F c -b -v -f C:\\BackupBanco\\Moria.backup Moria1" ).getInputStream();

                //lina de código Backup xp
               Runtime.getRuntime().exec("C:\\Arquivos de Programas\\PostgreSQL\\9.0\\bin\\pg_dump.exe -i -h localhost -p 5432 -U postgres -F c -b -v -f C:\\BackupBanco\\Moria.backup Moria1").getInputStream();
                JOptionPane.showMessageDialog(null, "Back Up Moria.backup gerado com sucesso!");
                System.exit(0);
            } catch (IOException ex) {
                ex.printStackTrace();

                JOptionPane.showMessageDialog(null, "Erro a tentar Gravar o registro..." + ex);
//                                
            }
//                            
//                            
        } else {

            System.exit(0);

        }


    }//GEN-LAST:event_Vendedor2ActionPerformed
    public static long carregarMemoria() {

        ArrayList<Integer> list = new ArrayList<Integer>();
        for (int i = 0; i < 1000000; i++) {
            list.add(i);
        }
        return Runtime.getRuntime().freeMemory();
    }
    private void ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoActionPerformed
        try {

            new CadastroProduto().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_ProdutoActionPerformed

    private void Cadastros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastros1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_Cadastros1ActionPerformed

    private void Vendedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendedor1ActionPerformed
        try {
// TODO add your handling code here:
            new CadastroCor().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_Vendedor1ActionPerformed

    private void Fornec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fornec1ActionPerformed
        try {
// TODO add your handling code here:
            new CadastroAviamento().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_Fornec1ActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        try {
// TODO add your handling code here:
            new CadastroTecido().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_TActionPerformed

    private void TerceirizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerceirizadaActionPerformed
// TODO add your handling code here:
        try {

// TODO add your handling code here:
            new CadastroTerceirizada().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_TerceirizadaActionPerformed

    private void VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendedorActionPerformed
// TODO add your handling code here:
        try {

// TODO add your handling code here:
            new CadastroVendedor().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_VendedorActionPerformed

    private void FornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FornecActionPerformed
// TODO add your handling code here:
        try {

// TODO add your handling code here:
            new CadastroFornecedor().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_FornecActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        try {

// TODO add your handling code here:
            new CadastroCliente().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ClienteActionPerformed

    private void ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_ConsultaActionPerformed

    private void CadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrosActionPerformed
// TODO add your handling code here:       
    }//GEN-LAST:event_CadastrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AReceber;
    private javax.swing.JMenuItem AReceberBalcao;
    private javax.swing.JMenuItem AReceberCarteira;
    private javax.swing.JMenuItem Apagar;
    private javax.swing.JMenuItem Aviam;
    private javax.swing.JMenuItem Aviamento;
    private javax.swing.JMenuItem CAniversario;
    private javax.swing.JMenuItem CBalanco;
    private javax.swing.JMenuItem CCliente;
    private javax.swing.JMenuItem CFechamentoProduto;
    private javax.swing.JMenuItem CFornecedor;
    private javax.swing.JMenuItem CGeral;
    private javax.swing.JMenuItem CMateriaPrima;
    private javax.swing.JMenuItem CMateriaPrima1;
    private javax.swing.JMenuItem CMostruario;
    private javax.swing.JMenuItem COrcamento;
    private javax.swing.JMenuItem CPedido;
    private javax.swing.JMenuItem CProdutoAcabado;
    private javax.swing.JMenuItem CTercerizada;
    private javax.swing.JMenuItem CVendedor;
    private javax.swing.JMenu Cadastros;
    private javax.swing.JMenu Cadastros1;
    private javax.swing.JMenu Cadastros2;
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenuItem Cliente2;
    private javax.swing.JMenu Consulta;
    private javax.swing.JMenu Contas;
    private javax.swing.JMenuItem Cor;
    private javax.swing.JMenuItem EntradaDireta;
    private javax.swing.JMenuItem Excluir;
    private javax.swing.JMenuItem FechamentoProduto;
    private javax.swing.JMenuItem Fornec;
    private javax.swing.JMenuItem Fornec1;
    private javax.swing.JMenuItem Liquid;
    private javax.swing.JMenuItem MateriaPri;
    private javax.swing.JMenuItem Mofit;
    private javax.swing.JMenuItem NotaFiscal;
    private javax.swing.JMenuItem Novo;
    private javax.swing.JMenuItem OrcamentoPedido;
    private javax.swing.JMenuItem Padrao;
    private javax.swing.JMenu Pedido;
    private javax.swing.JMenuItem Preco;
    private javax.swing.JMenuItem Produto;
    private javax.swing.JMenuItem Produto1;
    private javax.swing.JMenuItem ProdutoAcabado;
    private javax.swing.JMenu Relatorio;
    private javax.swing.JMenuItem SaidaMateriaPrima;
    private javax.swing.JMenuItem T;
    private javax.swing.JMenuItem Tec;
    private javax.swing.JMenuItem Tecido;
    private javax.swing.JMenuItem Terceirizada;
    private javax.swing.JMenu Usuario;
    private javax.swing.JMenu Utilitarios;
    private javax.swing.JMenuItem VendaBalcao;
    private javax.swing.JMenuItem VendaCarteira;
    private javax.swing.JMenuItem Vendedor;
    private javax.swing.JMenuItem Vendedor1;
    private javax.swing.JMenuItem Vendedor2;
    private javax.swing.JMenuItem Windows;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblimagem;
    public static javax.swing.JLabel lblusuario;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
